// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {IProgramFormEvaluator} from "../IProgramFormEvaluator.sol";

/// @notice Generated by the evaluator generator from spec/shapes/program.bin (the 12-word circuit).
///         The 12-word circuit's composition at z as straight-line code in 3 chunk contracts.
contract ShapesStraightEvaluatorAt is IProgramFormEvaluator {
    bytes32 private constant H0 = 0x93287206aec4bcb328581607e3ee57364acfcbdeccf88b2a1f7c18cbd4e86769;
    bytes32 private constant H1 = 0x49c63cd661201d82ac248b39a760fb592ebb5cc8f50e51f9d9763870cb61ccf8;
    bytes32 private constant H2 = 0x58ecbd2cdd3c419089384ec5a2a57e18e45baa881231ac9e07e6a4f554d3f63c;
    address private immutable C0;
    address private immutable C1;
    address private immutable C2;
    uint256 public constant N_PUBLIC = 36;

    error NotThisCircuit();
    error NonCanonical();
    error ChunkMismatch();

    constructor(address[] memory at) {
        if (at.length != 3) revert ChunkMismatch();
        C0 = _check(at[0], H0);
        C1 = _check(at[1], H1);
        C2 = _check(at[2], H2);
    }

    function _check(address a, bytes32 h) private view returns (address) {
        if (a.code.length == 0 || a.codehash != h) revert ChunkMismatch();
        return a;
    }

    function chunks() external view returns (address[] memory a) {
        a = new address[](3);
        a[0] = C0;
        a[1] = C1;
        a[2] = C2;
    }

    /// @inheritdoc IProgramFormEvaluator
    function evaluate(
        uint256[2][] calldata frame,
        uint256[2][] calldata periodic,
        uint256[2][] calldata coeffs,
        uint256[] calldata publics,
        uint256[6] calldata point
    ) external view returns (uint256, uint256) {
        {
            address C0_ = C0;
            address C1_ = C1;
            address C2_ = C2;
            assembly {
                mstore(0x49e0, C0_)
            mstore(0x4a00, C1_)
            mstore(0x4a20, C2_)
            }
        }
        assembly {
            function f2mul(a0, a1, b0, b1) -> r0, r1 {
                r0 := mod(add(mul(a0, b0), mul(7, mul(a1, b1))), 0xFFFFFFFF00000001)
                r1 := mod(add(mul(a0, b1), mul(a1, b0)), 0xFFFFFFFF00000001)
            }
            function sqn(x, n) -> r {
                r := x
                for {} n { n := sub(n, 1) } { r := mulmod(r, r, 0xFFFFFFFF00000001) }
            }
            function fpinv(a) -> r {
                let q := 0xFFFFFFFF00000001
                let x2 := mulmod(mulmod(a, a, q), a, q)
                let x3 := mulmod(mulmod(x2, x2, q), a, q)
                let x6 := mulmod(sqn(x3, 3), x3, q)
                let x12 := mulmod(sqn(x6, 6), x6, q)
                let x24 := mulmod(sqn(x12, 12), x12, q)
                let x30 := mulmod(sqn(x24, 6), x6, q)
                let x31 := mulmod(mulmod(x30, x30, q), a, q)
                let x32 := mulmod(mulmod(x31, x31, q), a, q)
                r := mulmod(sqn(x31, 33), x32, q)
            }
            function f2inv(a0, a1) -> r0, r1 {
                let q := 0xFFFFFFFF00000001
                let n := mod(add(mul(a0, a0), sub(0xffffffff000000010000000000000000000, mul(7, mul(a1, a1)))), q)
                if iszero(n) { revert(0, 0) }
                let i := fpinv(n)
                r0 := mulmod(a0, i, q)
                r1 := mulmod(sub(q, a1), i, q)
            }
            function trans(ca) {
                let s0 := 0
                let s1 := 0
                s0 := add(s0, mulmod(calldataload(add(ca, 0)), mload(0x3840), 0xffffffff00000001))
                s1 := add(s1, mulmod(calldataload(add(ca, 32)), mload(0x3840), 0xffffffff00000001))
                s0 := add(s0, mul(7, mulmod(calldataload(add(ca, 32)), mload(0x3860), 0xffffffff00000001)))
                s1 := add(s1, mulmod(calldataload(add(ca, 0)), mload(0x3860), 0xffffffff00000001))
                s0 := add(s0, mulmod(calldataload(add(ca, 64)), mload(0x3880), 0xffffffff00000001))
                s1 := add(s1, mulmod(calldataload(add(ca, 96)), mload(0x3880), 0xffffffff00000001))
                s0 := add(s0, mul(7, mulmod(calldataload(add(ca, 96)), mload(0x38a0), 0xffffffff00000001)))
                s1 := add(s1, mulmod(calldataload(add(ca, 64)), mload(0x38a0), 0xffffffff00000001))
                s0 := add(s0, mulmod(calldataload(add(ca, 128)), mload(0x3240), 0xffffffff00000001))
                s1 := add(s1, mulmod(calldataload(add(ca, 160)), mload(0x3240), 0xffffffff00000001))
                s0 := add(s0, mul(7, mulmod(calldataload(add(ca, 160)), mload(0x3260), 0xffffffff00000001)))
                s1 := add(s1, mulmod(calldataload(add(ca, 128)), mload(0x3260), 0xffffffff00000001))
                s0 := add(s0, mulmod(calldataload(add(ca, 192)), mload(0x3180), 0xffffffff00000001))
                s1 := add(s1, mulmod(calldataload(add(ca, 224)), mload(0x3180), 0xffffffff00000001))
                s0 := add(s0, mul(7, mulmod(calldataload(add(ca, 224)), mload(0x31a0), 0xffffffff00000001)))
                s1 := add(s1, mulmod(calldataload(add(ca, 192)), mload(0x31a0), 0xffffffff00000001))
                s0 := add(s0, mulmod(calldataload(add(ca, 256)), mload(0x3580), 0xffffffff00000001))
                s1 := add(s1, mulmod(calldataload(add(ca, 288)), mload(0x3580), 0xffffffff00000001))
                s0 := add(s0, mul(7, mulmod(calldataload(add(ca, 288)), mload(0x35a0), 0xffffffff00000001)))
                s1 := add(s1, mulmod(calldataload(add(ca, 256)), mload(0x35a0), 0xffffffff00000001))
                s0 := add(s0, mulmod(calldataload(add(ca, 320)), mload(0x35c0), 0xffffffff00000001))
                s1 := add(s1, mulmod(calldataload(add(ca, 352)), mload(0x35c0), 0xffffffff00000001))
                s0 := add(s0, mul(7, mulmod(calldataload(add(ca, 352)), mload(0x35e0), 0xffffffff00000001)))
                s1 := add(s1, mulmod(calldataload(add(ca, 320)), mload(0x35e0), 0xffffffff00000001))
                s0 := add(s0, mulmod(calldataload(add(ca, 384)), mload(0x3600), 0xffffffff00000001))
                s1 := add(s1, mulmod(calldataload(add(ca, 416)), mload(0x3600), 0xffffffff00000001))
                s0 := add(s0, mul(7, mulmod(calldataload(add(ca, 416)), mload(0x3620), 0xffffffff00000001)))
                s1 := add(s1, mulmod(calldataload(add(ca, 384)), mload(0x3620), 0xffffffff00000001))
                s0 := add(s0, mulmod(calldataload(add(ca, 448)), mload(0x3640), 0xffffffff00000001))
                s1 := add(s1, mulmod(calldataload(add(ca, 480)), mload(0x3640), 0xffffffff00000001))
                s0 := add(s0, mul(7, mulmod(calldataload(add(ca, 480)), mload(0x3660), 0xffffffff00000001)))
                s1 := add(s1, mulmod(calldataload(add(ca, 448)), mload(0x3660), 0xffffffff00000001))
                s0 := add(s0, mulmod(calldataload(add(ca, 512)), mload(0x3480), 0xffffffff00000001))
                s1 := add(s1, mulmod(calldataload(add(ca, 544)), mload(0x3480), 0xffffffff00000001))
                s0 := add(s0, mul(7, mulmod(calldataload(add(ca, 544)), mload(0x34a0), 0xffffffff00000001)))
                s1 := add(s1, mulmod(calldataload(add(ca, 512)), mload(0x34a0), 0xffffffff00000001))
                s0 := add(s0, mulmod(calldataload(add(ca, 576)), mload(0x3540), 0xffffffff00000001))
                s1 := add(s1, mulmod(calldataload(add(ca, 608)), mload(0x3540), 0xffffffff00000001))
                s0 := add(s0, mul(7, mulmod(calldataload(add(ca, 608)), mload(0x3560), 0xffffffff00000001)))
                s1 := add(s1, mulmod(calldataload(add(ca, 576)), mload(0x3560), 0xffffffff00000001))
                s0 := add(s0, mulmod(calldataload(add(ca, 640)), mload(0x3700), 0xffffffff00000001))
                s1 := add(s1, mulmod(calldataload(add(ca, 672)), mload(0x3700), 0xffffffff00000001))
                s0 := add(s0, mul(7, mulmod(calldataload(add(ca, 672)), mload(0x3720), 0xffffffff00000001)))
                s1 := add(s1, mulmod(calldataload(add(ca, 640)), mload(0x3720), 0xffffffff00000001))
                s0 := add(s0, mulmod(calldataload(add(ca, 704)), mload(0x36c0), 0xffffffff00000001))
                s1 := add(s1, mulmod(calldataload(add(ca, 736)), mload(0x36c0), 0xffffffff00000001))
                s0 := add(s0, mul(7, mulmod(calldataload(add(ca, 736)), mload(0x36e0), 0xffffffff00000001)))
                s1 := add(s1, mulmod(calldataload(add(ca, 704)), mload(0x36e0), 0xffffffff00000001))
                s0 := add(s0, mulmod(calldataload(add(ca, 768)), mload(0x3680), 0xffffffff00000001))
                s1 := add(s1, mulmod(calldataload(add(ca, 800)), mload(0x3680), 0xffffffff00000001))
                s0 := add(s0, mul(7, mulmod(calldataload(add(ca, 800)), mload(0x36a0), 0xffffffff00000001)))
                s1 := add(s1, mulmod(calldataload(add(ca, 768)), mload(0x36a0), 0xffffffff00000001))
                s0 := add(s0, mulmod(calldataload(add(ca, 832)), mload(0x30c0), 0xffffffff00000001))
                s1 := add(s1, mulmod(calldataload(add(ca, 864)), mload(0x30c0), 0xffffffff00000001))
                s0 := add(s0, mul(7, mulmod(calldataload(add(ca, 864)), mload(0x30e0), 0xffffffff00000001)))
                s1 := add(s1, mulmod(calldataload(add(ca, 832)), mload(0x30e0), 0xffffffff00000001))
                s0 := add(s0, mulmod(calldataload(add(ca, 896)), mload(0x38c0), 0xffffffff00000001))
                s1 := add(s1, mulmod(calldataload(add(ca, 928)), mload(0x38c0), 0xffffffff00000001))
                s0 := add(s0, mul(7, mulmod(calldataload(add(ca, 928)), mload(0x38e0), 0xffffffff00000001)))
                s1 := add(s1, mulmod(calldataload(add(ca, 896)), mload(0x38e0), 0xffffffff00000001))
                s0 := add(s0, mulmod(calldataload(add(ca, 960)), mload(0x3980), 0xffffffff00000001))
                s1 := add(s1, mulmod(calldataload(add(ca, 992)), mload(0x3980), 0xffffffff00000001))
                s0 := add(s0, mul(7, mulmod(calldataload(add(ca, 992)), mload(0x39a0), 0xffffffff00000001)))
                s1 := add(s1, mulmod(calldataload(add(ca, 960)), mload(0x39a0), 0xffffffff00000001))
                s0 := add(s0, mulmod(calldataload(add(ca, 1024)), mload(0x3a40), 0xffffffff00000001))
                s1 := add(s1, mulmod(calldataload(add(ca, 1056)), mload(0x3a40), 0xffffffff00000001))
                s0 := add(s0, mul(7, mulmod(calldataload(add(ca, 1056)), mload(0x3a60), 0xffffffff00000001)))
                s1 := add(s1, mulmod(calldataload(add(ca, 1024)), mload(0x3a60), 0xffffffff00000001))
                s0 := add(s0, mulmod(calldataload(add(ca, 1088)), mload(0x31c0), 0xffffffff00000001))
                s1 := add(s1, mulmod(calldataload(add(ca, 1120)), mload(0x31c0), 0xffffffff00000001))
                s0 := add(s0, mul(7, mulmod(calldataload(add(ca, 1120)), mload(0x31e0), 0xffffffff00000001)))
                s1 := add(s1, mulmod(calldataload(add(ca, 1088)), mload(0x31e0), 0xffffffff00000001))
                s0 := add(s0, mulmod(calldataload(add(ca, 1152)), mload(0x3280), 0xffffffff00000001))
                s1 := add(s1, mulmod(calldataload(add(ca, 1184)), mload(0x3280), 0xffffffff00000001))
                s0 := add(s0, mul(7, mulmod(calldataload(add(ca, 1184)), mload(0x32a0), 0xffffffff00000001)))
                s1 := add(s1, mulmod(calldataload(add(ca, 1152)), mload(0x32a0), 0xffffffff00000001))
                s0 := add(s0, mulmod(calldataload(add(ca, 1216)), mload(0x3340), 0xffffffff00000001))
                s1 := add(s1, mulmod(calldataload(add(ca, 1248)), mload(0x3340), 0xffffffff00000001))
                s0 := add(s0, mul(7, mulmod(calldataload(add(ca, 1248)), mload(0x3360), 0xffffffff00000001)))
                s1 := add(s1, mulmod(calldataload(add(ca, 1216)), mload(0x3360), 0xffffffff00000001))
                s0 := add(s0, mulmod(calldataload(add(ca, 1280)), mload(0x3400), 0xffffffff00000001))
                s1 := add(s1, mulmod(calldataload(add(ca, 1312)), mload(0x3400), 0xffffffff00000001))
                s0 := add(s0, mul(7, mulmod(calldataload(add(ca, 1312)), mload(0x3420), 0xffffffff00000001)))
                s1 := add(s1, mulmod(calldataload(add(ca, 1280)), mload(0x3420), 0xffffffff00000001))
                s0 := add(s0, mulmod(calldataload(add(ca, 1344)), mload(0x34c0), 0xffffffff00000001))
                s1 := add(s1, mulmod(calldataload(add(ca, 1376)), mload(0x34c0), 0xffffffff00000001))
                s0 := add(s0, mul(7, mulmod(calldataload(add(ca, 1376)), mload(0x34e0), 0xffffffff00000001)))
                s1 := add(s1, mulmod(calldataload(add(ca, 1344)), mload(0x34e0), 0xffffffff00000001))
                s0 := add(s0, mulmod(calldataload(add(ca, 1408)), mload(0x3900), 0xffffffff00000001))
                s1 := add(s1, mulmod(calldataload(add(ca, 1440)), mload(0x3900), 0xffffffff00000001))
                s0 := add(s0, mul(7, mulmod(calldataload(add(ca, 1440)), mload(0x3920), 0xffffffff00000001)))
                s1 := add(s1, mulmod(calldataload(add(ca, 1408)), mload(0x3920), 0xffffffff00000001))
                s0 := add(s0, mulmod(calldataload(add(ca, 1472)), mload(0x39c0), 0xffffffff00000001))
                s1 := add(s1, mulmod(calldataload(add(ca, 1504)), mload(0x39c0), 0xffffffff00000001))
                s0 := add(s0, mul(7, mulmod(calldataload(add(ca, 1504)), mload(0x39e0), 0xffffffff00000001)))
                s1 := add(s1, mulmod(calldataload(add(ca, 1472)), mload(0x39e0), 0xffffffff00000001))
                s0 := add(s0, mulmod(calldataload(add(ca, 1536)), mload(0x3a80), 0xffffffff00000001))
                s1 := add(s1, mulmod(calldataload(add(ca, 1568)), mload(0x3a80), 0xffffffff00000001))
                s0 := add(s0, mul(7, mulmod(calldataload(add(ca, 1568)), mload(0x3aa0), 0xffffffff00000001)))
                s1 := add(s1, mulmod(calldataload(add(ca, 1536)), mload(0x3aa0), 0xffffffff00000001))
                s0 := add(s0, mulmod(calldataload(add(ca, 1600)), mload(0x3200), 0xffffffff00000001))
                s1 := add(s1, mulmod(calldataload(add(ca, 1632)), mload(0x3200), 0xffffffff00000001))
                s0 := add(s0, mul(7, mulmod(calldataload(add(ca, 1632)), mload(0x3220), 0xffffffff00000001)))
                s1 := add(s1, mulmod(calldataload(add(ca, 1600)), mload(0x3220), 0xffffffff00000001))
                s0 := add(s0, mulmod(calldataload(add(ca, 1664)), mload(0x32c0), 0xffffffff00000001))
                s1 := add(s1, mulmod(calldataload(add(ca, 1696)), mload(0x32c0), 0xffffffff00000001))
                s0 := add(s0, mul(7, mulmod(calldataload(add(ca, 1696)), mload(0x32e0), 0xffffffff00000001)))
                s1 := add(s1, mulmod(calldataload(add(ca, 1664)), mload(0x32e0), 0xffffffff00000001))
                s0 := add(s0, mulmod(calldataload(add(ca, 1728)), mload(0x3380), 0xffffffff00000001))
                s1 := add(s1, mulmod(calldataload(add(ca, 1760)), mload(0x3380), 0xffffffff00000001))
                s0 := add(s0, mul(7, mulmod(calldataload(add(ca, 1760)), mload(0x33a0), 0xffffffff00000001)))
                s1 := add(s1, mulmod(calldataload(add(ca, 1728)), mload(0x33a0), 0xffffffff00000001))
                s0 := add(s0, mulmod(calldataload(add(ca, 1792)), mload(0x3440), 0xffffffff00000001))
                s1 := add(s1, mulmod(calldataload(add(ca, 1824)), mload(0x3440), 0xffffffff00000001))
                s0 := add(s0, mul(7, mulmod(calldataload(add(ca, 1824)), mload(0x3460), 0xffffffff00000001)))
                s1 := add(s1, mulmod(calldataload(add(ca, 1792)), mload(0x3460), 0xffffffff00000001))
                s0 := add(s0, mulmod(calldataload(add(ca, 1856)), mload(0x3500), 0xffffffff00000001))
                s1 := add(s1, mulmod(calldataload(add(ca, 1888)), mload(0x3500), 0xffffffff00000001))
                s0 := add(s0, mul(7, mulmod(calldataload(add(ca, 1888)), mload(0x3520), 0xffffffff00000001)))
                s1 := add(s1, mulmod(calldataload(add(ca, 1856)), mload(0x3520), 0xffffffff00000001))
                s0 := add(s0, mulmod(calldataload(add(ca, 1920)), mload(0x3740), 0xffffffff00000001))
                s1 := add(s1, mulmod(calldataload(add(ca, 1952)), mload(0x3740), 0xffffffff00000001))
                s0 := add(s0, mul(7, mulmod(calldataload(add(ca, 1952)), mload(0x3760), 0xffffffff00000001)))
                s1 := add(s1, mulmod(calldataload(add(ca, 1920)), mload(0x3760), 0xffffffff00000001))
                s0 := add(s0, mulmod(calldataload(add(ca, 1984)), mload(0x3000), 0xffffffff00000001))
                s1 := add(s1, mulmod(calldataload(add(ca, 2016)), mload(0x3000), 0xffffffff00000001))
                s0 := add(s0, mul(7, mulmod(calldataload(add(ca, 2016)), mload(0x3020), 0xffffffff00000001)))
                s1 := add(s1, mulmod(calldataload(add(ca, 1984)), mload(0x3020), 0xffffffff00000001))
                s0 := add(s0, mulmod(calldataload(add(ca, 2048)), mload(0x3780), 0xffffffff00000001))
                s1 := add(s1, mulmod(calldataload(add(ca, 2080)), mload(0x3780), 0xffffffff00000001))
                s0 := add(s0, mul(7, mulmod(calldataload(add(ca, 2080)), mload(0x37a0), 0xffffffff00000001)))
                s1 := add(s1, mulmod(calldataload(add(ca, 2048)), mload(0x37a0), 0xffffffff00000001))
                s0 := add(s0, mulmod(calldataload(add(ca, 2112)), mload(0x37c0), 0xffffffff00000001))
                s1 := add(s1, mulmod(calldataload(add(ca, 2144)), mload(0x37c0), 0xffffffff00000001))
                s0 := add(s0, mul(7, mulmod(calldataload(add(ca, 2144)), mload(0x37e0), 0xffffffff00000001)))
                s1 := add(s1, mulmod(calldataload(add(ca, 2112)), mload(0x37e0), 0xffffffff00000001))
                s0 := add(s0, mulmod(calldataload(add(ca, 2176)), mload(0x3800), 0xffffffff00000001))
                s1 := add(s1, mulmod(calldataload(add(ca, 2208)), mload(0x3800), 0xffffffff00000001))
                s0 := add(s0, mul(7, mulmod(calldataload(add(ca, 2208)), mload(0x3820), 0xffffffff00000001)))
                s1 := add(s1, mulmod(calldataload(add(ca, 2176)), mload(0x3820), 0xffffffff00000001))
                s0 := add(s0, mulmod(calldataload(add(ca, 2240)), mload(0x3fc0), 0xffffffff00000001))
                s1 := add(s1, mulmod(calldataload(add(ca, 2272)), mload(0x3fc0), 0xffffffff00000001))
                s0 := add(s0, mul(7, mulmod(calldataload(add(ca, 2272)), mload(0x3fe0), 0xffffffff00000001)))
                s1 := add(s1, mulmod(calldataload(add(ca, 2240)), mload(0x3fe0), 0xffffffff00000001))
                s0 := add(s0, mulmod(calldataload(add(ca, 2304)), mload(0x3e80), 0xffffffff00000001))
                s1 := add(s1, mulmod(calldataload(add(ca, 2336)), mload(0x3e80), 0xffffffff00000001))
                s0 := add(s0, mul(7, mulmod(calldataload(add(ca, 2336)), mload(0x3ea0), 0xffffffff00000001)))
                s1 := add(s1, mulmod(calldataload(add(ca, 2304)), mload(0x3ea0), 0xffffffff00000001))
                s0 := add(s0, mulmod(calldataload(add(ca, 2368)), mload(0x43c0), 0xffffffff00000001))
                s1 := add(s1, mulmod(calldataload(add(ca, 2400)), mload(0x43c0), 0xffffffff00000001))
                s0 := add(s0, mul(7, mulmod(calldataload(add(ca, 2400)), mload(0x43e0), 0xffffffff00000001)))
                s1 := add(s1, mulmod(calldataload(add(ca, 2368)), mload(0x43e0), 0xffffffff00000001))
                s0 := add(s0, mulmod(calldataload(add(ca, 2432)), mload(0x2c40), 0xffffffff00000001))
                s1 := add(s1, mulmod(calldataload(add(ca, 2464)), mload(0x2c40), 0xffffffff00000001))
                s0 := add(s0, mul(7, mulmod(calldataload(add(ca, 2464)), mload(0x2c60), 0xffffffff00000001)))
                s1 := add(s1, mulmod(calldataload(add(ca, 2432)), mload(0x2c60), 0xffffffff00000001))
                s0 := add(s0, mulmod(calldataload(add(ca, 2496)), mload(0x33c0), 0xffffffff00000001))
                s1 := add(s1, mulmod(calldataload(add(ca, 2528)), mload(0x33c0), 0xffffffff00000001))
                s0 := add(s0, mul(7, mulmod(calldataload(add(ca, 2528)), mload(0x33e0), 0xffffffff00000001)))
                s1 := add(s1, mulmod(calldataload(add(ca, 2496)), mload(0x33e0), 0xffffffff00000001))
                s0 := add(s0, mulmod(calldataload(add(ca, 2560)), mload(0x48c0), 0xffffffff00000001))
                s1 := add(s1, mulmod(calldataload(add(ca, 2592)), mload(0x48c0), 0xffffffff00000001))
                s0 := add(s0, mul(7, mulmod(calldataload(add(ca, 2592)), mload(0x48e0), 0xffffffff00000001)))
                s1 := add(s1, mulmod(calldataload(add(ca, 2560)), mload(0x48e0), 0xffffffff00000001))
                s0 := add(s0, mulmod(calldataload(add(ca, 2624)), mload(0x2f00), 0xffffffff00000001))
                s1 := add(s1, mulmod(calldataload(add(ca, 2656)), mload(0x2f00), 0xffffffff00000001))
                s0 := add(s0, mul(7, mulmod(calldataload(add(ca, 2656)), mload(0x2f20), 0xffffffff00000001)))
                s1 := add(s1, mulmod(calldataload(add(ca, 2624)), mload(0x2f20), 0xffffffff00000001))
                s0 := add(s0, mulmod(calldataload(add(ca, 2688)), mload(0x4480), 0xffffffff00000001))
                s1 := add(s1, mulmod(calldataload(add(ca, 2720)), mload(0x4480), 0xffffffff00000001))
                s0 := add(s0, mul(7, mulmod(calldataload(add(ca, 2720)), mload(0x44a0), 0xffffffff00000001)))
                s1 := add(s1, mulmod(calldataload(add(ca, 2688)), mload(0x44a0), 0xffffffff00000001))
                let e0 := 1
                let e1 := 0
                e0, e1 := f2mul(e0, e1, addmod(mload(0x2640), 14478376679624396471, 0xffffffff00000001), mload(0x2660))
                s0, s1 := f2mul(mod(s0, 0xffffffff00000001), mod(s1, 0xffffffff00000001), e0, e1)
                mstore(0x4900, s0)
                mstore(0x4920, s1)
                let h0 := mload(0x2640)
                let h1 := mload(0x2660)
                for { let k := 13 } k { k := sub(k, 1) } {
                    let q0 := mod(add(mul(h0, h0), mul(7, mul(h1, h1))), 0xffffffff00000001)
                    h1 := mulmod(add(h1, h1), h0, 0xffffffff00000001)
                    h0 := q0
                }
                mstore(0x4940, addmod(h0, 18446744069414584320, 0xffffffff00000001))
                mstore(0x4960, h1)
            }
            function bnd(ca, pu) -> n0, n1, dd {
                let z1 := mload(0x2660)
                let w7 := mulmod(7, mulmod(z1, z1, 0xffffffff00000001), 0xffffffff00000001)
                dd := 1
                {
                    let r0 := 0
                    let r1 := 0
                    r0 := add(r0, add(mulmod(calldataload(add(ca, 2752)), add(mload(0x80), 0), 0xffffffff00000001), mul(7, mulmod(calldataload(add(ca, 2784)), mload(0xa0), 0xffffffff00000001))))
                    r1 := add(r1, add(mulmod(calldataload(add(ca, 2752)), mload(0xa0), 0xffffffff00000001), mulmod(calldataload(add(ca, 2784)), add(mload(0x80), 0), 0xffffffff00000001)))
                    r0 := add(r0, add(mulmod(calldataload(add(ca, 2816)), add(mload(0x180), 0), 0xffffffff00000001), mul(7, mulmod(calldataload(add(ca, 2848)), mload(0x1a0), 0xffffffff00000001))))
                    r1 := add(r1, add(mulmod(calldataload(add(ca, 2816)), mload(0x1a0), 0xffffffff00000001), mulmod(calldataload(add(ca, 2848)), add(mload(0x180), 0), 0xffffffff00000001)))
                    r0 := add(r0, add(mulmod(calldataload(add(ca, 5696)), add(mload(0x900), 18446744069414584320), 0xffffffff00000001), mul(7, mulmod(calldataload(add(ca, 5728)), mload(0x920), 0xffffffff00000001))))
                    r1 := add(r1, add(mulmod(calldataload(add(ca, 5696)), mload(0x920), 0xffffffff00000001), mulmod(calldataload(add(ca, 5728)), add(mload(0x900), 18446744069414584320), 0xffffffff00000001)))
                    r0 := add(r0, add(mulmod(calldataload(add(ca, 5760)), add(mload(0x940), 0), 0xffffffff00000001), mul(7, mulmod(calldataload(add(ca, 5792)), mload(0x960), 0xffffffff00000001))))
                    r1 := add(r1, add(mulmod(calldataload(add(ca, 5760)), mload(0x960), 0xffffffff00000001), mulmod(calldataload(add(ca, 5792)), add(mload(0x940), 0), 0xffffffff00000001)))
                    r0 := add(r0, add(mulmod(calldataload(add(ca, 5952)), add(mload(0x980), 18446744069414584320), 0xffffffff00000001), mul(7, mulmod(calldataload(add(ca, 5984)), mload(0x9a0), 0xffffffff00000001))))
                    r1 := add(r1, add(mulmod(calldataload(add(ca, 5952)), mload(0x9a0), 0xffffffff00000001), mulmod(calldataload(add(ca, 5984)), add(mload(0x980), 18446744069414584320), 0xffffffff00000001)))
                    r0 := add(r0, add(mulmod(calldataload(add(ca, 6016)), add(mload(0x9c0), 0), 0xffffffff00000001), mul(7, mulmod(calldataload(add(ca, 6048)), mload(0x9e0), 0xffffffff00000001))))
                    r1 := add(r1, add(mulmod(calldataload(add(ca, 6016)), mload(0x9e0), 0xffffffff00000001), mulmod(calldataload(add(ca, 6048)), add(mload(0x9c0), 0), 0xffffffff00000001)))
                    r0 := add(r0, add(mulmod(calldataload(add(ca, 6208)), add(mload(0xa00), 18446744069414584320), 0xffffffff00000001), mul(7, mulmod(calldataload(add(ca, 6240)), mload(0xa20), 0xffffffff00000001))))
                    r1 := add(r1, add(mulmod(calldataload(add(ca, 6208)), mload(0xa20), 0xffffffff00000001), mulmod(calldataload(add(ca, 6240)), add(mload(0xa00), 18446744069414584320), 0xffffffff00000001)))
                    r0 := add(r0, add(mulmod(calldataload(add(ca, 6272)), add(mload(0xa40), 0), 0xffffffff00000001), mul(7, mulmod(calldataload(add(ca, 6304)), mload(0xa60), 0xffffffff00000001))))
                    r1 := add(r1, add(mulmod(calldataload(add(ca, 6272)), mload(0xa60), 0xffffffff00000001), mulmod(calldataload(add(ca, 6304)), add(mload(0xa40), 0), 0xffffffff00000001)))
                    r0 := add(r0, add(mulmod(calldataload(add(ca, 6464)), add(mload(0xa80), 18446744069414584320), 0xffffffff00000001), mul(7, mulmod(calldataload(add(ca, 6496)), mload(0xaa0), 0xffffffff00000001))))
                    r1 := add(r1, add(mulmod(calldataload(add(ca, 6464)), mload(0xaa0), 0xffffffff00000001), mulmod(calldataload(add(ca, 6496)), add(mload(0xa80), 18446744069414584320), 0xffffffff00000001)))
                    r0 := add(r0, add(mulmod(calldataload(add(ca, 6528)), add(mload(0xac0), 0), 0xffffffff00000001), mul(7, mulmod(calldataload(add(ca, 6560)), mload(0xae0), 0xffffffff00000001))))
                    r1 := add(r1, add(mulmod(calldataload(add(ca, 6528)), mload(0xae0), 0xffffffff00000001), mulmod(calldataload(add(ca, 6560)), add(mload(0xac0), 0), 0xffffffff00000001)))
                    r0 := mod(r0, 0xffffffff00000001)
                    r1 := mod(r1, 0xffffffff00000001)
                    let d0 := addmod(mload(0x2640), 18446744069414584320, 0xffffffff00000001)
                    let nr := mod(add(mul(d0, d0), sub(0xffffffff00000001, w7)), 0xffffffff00000001)
                    n0 := mod(add(mul(n0, nr), mul(mod(add(mul(r0, d0), sub(0xffffffff000000010000000000000000000, mul(7, mul(r1, z1)))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    n1 := mod(add(mul(n1, nr), mul(mod(add(mul(r1, d0), sub(0xffffffff000000010000000000000000000, mul(r0, z1))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    dd := mulmod(dd, nr, 0xffffffff00000001)
                }
                {
                    let r0 := 0
                    let r1 := 0
                    r0 := add(r0, add(mulmod(calldataload(add(ca, 2880)), add(mload(0x80), 0), 0xffffffff00000001), mul(7, mulmod(calldataload(add(ca, 2912)), mload(0xa0), 0xffffffff00000001))))
                    r1 := add(r1, add(mulmod(calldataload(add(ca, 2880)), mload(0xa0), 0xffffffff00000001), mulmod(calldataload(add(ca, 2912)), add(mload(0x80), 0), 0xffffffff00000001)))
                    r0 := mod(r0, 0xffffffff00000001)
                    r1 := mod(r1, 0xffffffff00000001)
                    let d0 := addmod(mload(0x2640), 1415419453610921553, 0xffffffff00000001)
                    let nr := mod(add(mul(d0, d0), sub(0xffffffff00000001, w7)), 0xffffffff00000001)
                    n0 := mod(add(mul(n0, nr), mul(mod(add(mul(r0, d0), sub(0xffffffff000000010000000000000000000, mul(7, mul(r1, z1)))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    n1 := mod(add(mul(n1, nr), mul(mod(add(mul(r1, d0), sub(0xffffffff000000010000000000000000000, mul(r0, z1))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    dd := mulmod(dd, nr, 0xffffffff00000001)
                }
                {
                    let r0 := 0
                    let r1 := 0
                    r0 := add(r0, add(mulmod(calldataload(add(ca, 2944)), add(mload(0x80), 0), 0xffffffff00000001), mul(7, mulmod(calldataload(add(ca, 2976)), mload(0xa0), 0xffffffff00000001))))
                    r1 := add(r1, add(mulmod(calldataload(add(ca, 2944)), mload(0xa0), 0xffffffff00000001), mulmod(calldataload(add(ca, 2976)), add(mload(0x80), 0), 0xffffffff00000001)))
                    r0 := mod(r0, 0xffffffff00000001)
                    r1 := mod(r1, 0xffffffff00000001)
                    let d0 := addmod(mload(0x2640), 15975288260888972401, 0xffffffff00000001)
                    let nr := mod(add(mul(d0, d0), sub(0xffffffff00000001, w7)), 0xffffffff00000001)
                    n0 := mod(add(mul(n0, nr), mul(mod(add(mul(r0, d0), sub(0xffffffff000000010000000000000000000, mul(7, mul(r1, z1)))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    n1 := mod(add(mul(n1, nr), mul(mod(add(mul(r1, d0), sub(0xffffffff000000010000000000000000000, mul(r0, z1))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    dd := mulmod(dd, nr, 0xffffffff00000001)
                }
                {
                    let r0 := 0
                    let r1 := 0
                    r0 := add(r0, add(mulmod(calldataload(add(ca, 3008)), add(mload(0x180), 18446744068016812477), 0xffffffff00000001), mul(7, mulmod(calldataload(add(ca, 3040)), mload(0x1a0), 0xffffffff00000001))))
                    r1 := add(r1, add(mulmod(calldataload(add(ca, 3008)), mload(0x1a0), 0xffffffff00000001), mulmod(calldataload(add(ca, 3040)), add(mload(0x180), 18446744068016812477), 0xffffffff00000001)))
                    r0 := add(r0, add(mulmod(calldataload(add(ca, 3136)), add(mload(0x1c0), 0), 0xffffffff00000001), mul(7, mulmod(calldataload(add(ca, 3168)), mload(0x1e0), 0xffffffff00000001))))
                    r1 := add(r1, add(mulmod(calldataload(add(ca, 3136)), mload(0x1e0), 0xffffffff00000001), mulmod(calldataload(add(ca, 3168)), add(mload(0x1c0), 0), 0xffffffff00000001)))
                    r0 := mod(r0, 0xffffffff00000001)
                    r1 := mod(r1, 0xffffffff00000001)
                    let d0 := addmod(mload(0x2640), 2761102078703419584, 0xffffffff00000001)
                    let nr := mod(add(mul(d0, d0), sub(0xffffffff00000001, w7)), 0xffffffff00000001)
                    n0 := mod(add(mul(n0, nr), mul(mod(add(mul(r0, d0), sub(0xffffffff000000010000000000000000000, mul(7, mul(r1, z1)))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    n1 := mod(add(mul(n1, nr), mul(mod(add(mul(r1, d0), sub(0xffffffff000000010000000000000000000, mul(r0, z1))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    dd := mulmod(dd, nr, 0xffffffff00000001)
                }
                {
                    let r0 := 0
                    let r1 := 0
                    r0 := add(r0, add(mulmod(calldataload(add(ca, 3072)), add(mload(0x180), 18446744068100371381), 0xffffffff00000001), mul(7, mulmod(calldataload(add(ca, 3104)), mload(0x1a0), 0xffffffff00000001))))
                    r1 := add(r1, add(mulmod(calldataload(add(ca, 3072)), mload(0x1a0), 0xffffffff00000001), mulmod(calldataload(add(ca, 3104)), add(mload(0x180), 18446744068100371381), 0xffffffff00000001)))
                    r0 := mod(r0, 0xffffffff00000001)
                    r1 := mod(r1, 0xffffffff00000001)
                    let d0 := addmod(mload(0x2640), 4212621207229430630, 0xffffffff00000001)
                    let nr := mod(add(mul(d0, d0), sub(0xffffffff00000001, w7)), 0xffffffff00000001)
                    n0 := mod(add(mul(n0, nr), mul(mod(add(mul(r0, d0), sub(0xffffffff000000010000000000000000000, mul(7, mul(r1, z1)))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    n1 := mod(add(mul(n1, nr), mul(mod(add(mul(r1, d0), sub(0xffffffff000000010000000000000000000, mul(r0, z1))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    dd := mulmod(dd, nr, 0xffffffff00000001)
                }
                {
                    let r0 := 0
                    let r1 := 0
                    r0 := add(r0, add(mulmod(calldataload(add(ca, 3200)), add(mload(0x180), 18446744068016812477), 0xffffffff00000001), mul(7, mulmod(calldataload(add(ca, 3232)), mload(0x1a0), 0xffffffff00000001))))
                    r1 := add(r1, add(mulmod(calldataload(add(ca, 3200)), mload(0x1a0), 0xffffffff00000001), mulmod(calldataload(add(ca, 3232)), add(mload(0x180), 18446744068016812477), 0xffffffff00000001)))
                    r0 := add(r0, add(mulmod(calldataload(add(ca, 3328)), add(mload(0x1c0), 0), 0xffffffff00000001), mul(7, mulmod(calldataload(add(ca, 3360)), mload(0x1e0), 0xffffffff00000001))))
                    r1 := add(r1, add(mulmod(calldataload(add(ca, 3328)), mload(0x1e0), 0xffffffff00000001), mulmod(calldataload(add(ca, 3360)), add(mload(0x1c0), 0), 0xffffffff00000001)))
                    r0 := mod(r0, 0xffffffff00000001)
                    r1 := mod(r1, 0xffffffff00000001)
                    let d0 := addmod(mload(0x2640), 8083950796479296659, 0xffffffff00000001)
                    let nr := mod(add(mul(d0, d0), sub(0xffffffff00000001, w7)), 0xffffffff00000001)
                    n0 := mod(add(mul(n0, nr), mul(mod(add(mul(r0, d0), sub(0xffffffff000000010000000000000000000, mul(7, mul(r1, z1)))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    n1 := mod(add(mul(n1, nr), mul(mod(add(mul(r1, d0), sub(0xffffffff000000010000000000000000000, mul(r0, z1))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    dd := mulmod(dd, nr, 0xffffffff00000001)
                }
                {
                    let r0 := 0
                    let r1 := 0
                    r0 := add(r0, add(mulmod(calldataload(add(ca, 3264)), add(mload(0x180), 18446744068100371381), 0xffffffff00000001), mul(7, mulmod(calldataload(add(ca, 3296)), mload(0x1a0), 0xffffffff00000001))))
                    r1 := add(r1, add(mulmod(calldataload(add(ca, 3264)), mload(0x1a0), 0xffffffff00000001), mulmod(calldataload(add(ca, 3296)), add(mload(0x180), 18446744068100371381), 0xffffffff00000001)))
                    r0 := mod(r0, 0xffffffff00000001)
                    r1 := mod(r1, 0xffffffff00000001)
                    let d0 := addmod(mload(0x2640), 18363833618917996149, 0xffffffff00000001)
                    let nr := mod(add(mul(d0, d0), sub(0xffffffff00000001, w7)), 0xffffffff00000001)
                    n0 := mod(add(mul(n0, nr), mul(mod(add(mul(r0, d0), sub(0xffffffff000000010000000000000000000, mul(7, mul(r1, z1)))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    n1 := mod(add(mul(n1, nr), mul(mod(add(mul(r1, d0), sub(0xffffffff000000010000000000000000000, mul(r0, z1))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    dd := mulmod(dd, nr, 0xffffffff00000001)
                }
                {
                    let r0 := 0
                    let r1 := 0
                    r0 := add(r0, add(mulmod(calldataload(add(ca, 3392)), add(mload(0x80), sub(0xffffffff00000001, calldataload(add(pu, 0)))), 0xffffffff00000001), mul(7, mulmod(calldataload(add(ca, 3424)), mload(0xa0), 0xffffffff00000001))))
                    r1 := add(r1, add(mulmod(calldataload(add(ca, 3392)), mload(0xa0), 0xffffffff00000001), mulmod(calldataload(add(ca, 3424)), add(mload(0x80), sub(0xffffffff00000001, calldataload(add(pu, 0)))), 0xffffffff00000001)))
                    r0 := mod(r0, 0xffffffff00000001)
                    r1 := mod(r1, 0xffffffff00000001)
                    let d0 := addmod(mload(0x2640), 9402811212061249573, 0xffffffff00000001)
                    let nr := mod(add(mul(d0, d0), sub(0xffffffff00000001, w7)), 0xffffffff00000001)
                    n0 := mod(add(mul(n0, nr), mul(mod(add(mul(r0, d0), sub(0xffffffff000000010000000000000000000, mul(7, mul(r1, z1)))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    n1 := mod(add(mul(n1, nr), mul(mod(add(mul(r1, d0), sub(0xffffffff000000010000000000000000000, mul(r0, z1))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    dd := mulmod(dd, nr, 0xffffffff00000001)
                }
                {
                    let r0 := 0
                    let r1 := 0
                    r0 := add(r0, add(mulmod(calldataload(add(ca, 3456)), add(mload(0x80), sub(0xffffffff00000001, calldataload(add(pu, 32)))), 0xffffffff00000001), mul(7, mulmod(calldataload(add(ca, 3488)), mload(0xa0), 0xffffffff00000001))))
                    r1 := add(r1, add(mulmod(calldataload(add(ca, 3456)), mload(0xa0), 0xffffffff00000001), mulmod(calldataload(add(ca, 3488)), add(mload(0x80), sub(0xffffffff00000001, calldataload(add(pu, 32)))), 0xffffffff00000001)))
                    r0 := mod(r0, 0xffffffff00000001)
                    r1 := mod(r1, 0xffffffff00000001)
                    let d0 := addmod(mload(0x2640), 13447871778869718167, 0xffffffff00000001)
                    let nr := mod(add(mul(d0, d0), sub(0xffffffff00000001, w7)), 0xffffffff00000001)
                    n0 := mod(add(mul(n0, nr), mul(mod(add(mul(r0, d0), sub(0xffffffff000000010000000000000000000, mul(7, mul(r1, z1)))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    n1 := mod(add(mul(n1, nr), mul(mod(add(mul(r1, d0), sub(0xffffffff000000010000000000000000000, mul(r0, z1))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    dd := mulmod(dd, nr, 0xffffffff00000001)
                }
                {
                    let r0 := 0
                    let r1 := 0
                    r0 := add(r0, add(mulmod(calldataload(add(ca, 3520)), add(mload(0x80), sub(0xffffffff00000001, calldataload(add(pu, 64)))), 0xffffffff00000001), mul(7, mulmod(calldataload(add(ca, 3552)), mload(0xa0), 0xffffffff00000001))))
                    r1 := add(r1, add(mulmod(calldataload(add(ca, 3520)), mload(0xa0), 0xffffffff00000001), mulmod(calldataload(add(ca, 3552)), add(mload(0x80), sub(0xffffffff00000001, calldataload(add(pu, 64)))), 0xffffffff00000001)))
                    r0 := mod(r0, 0xffffffff00000001)
                    r1 := mod(r1, 0xffffffff00000001)
                    let d0 := addmod(mload(0x2640), 2719505159006863752, 0xffffffff00000001)
                    let nr := mod(add(mul(d0, d0), sub(0xffffffff00000001, w7)), 0xffffffff00000001)
                    n0 := mod(add(mul(n0, nr), mul(mod(add(mul(r0, d0), sub(0xffffffff000000010000000000000000000, mul(7, mul(r1, z1)))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    n1 := mod(add(mul(n1, nr), mul(mod(add(mul(r1, d0), sub(0xffffffff000000010000000000000000000, mul(r0, z1))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    dd := mulmod(dd, nr, 0xffffffff00000001)
                }
                {
                    let r0 := 0
                    let r1 := 0
                    r0 := add(r0, add(mulmod(calldataload(add(ca, 3584)), add(mload(0x80), sub(0xffffffff00000001, calldataload(add(pu, 96)))), 0xffffffff00000001), mul(7, mulmod(calldataload(add(ca, 3616)), mload(0xa0), 0xffffffff00000001))))
                    r1 := add(r1, add(mulmod(calldataload(add(ca, 3584)), mload(0xa0), 0xffffffff00000001), mulmod(calldataload(add(ca, 3616)), add(mload(0x80), sub(0xffffffff00000001, calldataload(add(pu, 96)))), 0xffffffff00000001)))
                    r0 := mod(r0, 0xffffffff00000001)
                    r1 := mod(r1, 0xffffffff00000001)
                    let d0 := addmod(mload(0x2640), 2777864605899302133, 0xffffffff00000001)
                    let nr := mod(add(mul(d0, d0), sub(0xffffffff00000001, w7)), 0xffffffff00000001)
                    n0 := mod(add(mul(n0, nr), mul(mod(add(mul(r0, d0), sub(0xffffffff000000010000000000000000000, mul(7, mul(r1, z1)))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    n1 := mod(add(mul(n1, nr), mul(mod(add(mul(r1, d0), sub(0xffffffff000000010000000000000000000, mul(r0, z1))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    dd := mulmod(dd, nr, 0xffffffff00000001)
                }
                {
                    let r0 := 0
                    let r1 := 0
                    r0 := add(r0, add(mulmod(calldataload(add(ca, 3648)), add(mload(0x80), sub(0xffffffff00000001, calldataload(add(pu, 128)))), 0xffffffff00000001), mul(7, mulmod(calldataload(add(ca, 3680)), mload(0xa0), 0xffffffff00000001))))
                    r1 := add(r1, add(mulmod(calldataload(add(ca, 3648)), mload(0xa0), 0xffffffff00000001), mulmod(calldataload(add(ca, 3680)), add(mload(0x80), sub(0xffffffff00000001, calldataload(add(pu, 128)))), 0xffffffff00000001)))
                    r0 := mod(r0, 0xffffffff00000001)
                    r1 := mod(r1, 0xffffffff00000001)
                    let d0 := addmod(mload(0x2640), 4716406379463037818, 0xffffffff00000001)
                    let nr := mod(add(mul(d0, d0), sub(0xffffffff00000001, w7)), 0xffffffff00000001)
                    n0 := mod(add(mul(n0, nr), mul(mod(add(mul(r0, d0), sub(0xffffffff000000010000000000000000000, mul(7, mul(r1, z1)))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    n1 := mod(add(mul(n1, nr), mul(mod(add(mul(r1, d0), sub(0xffffffff000000010000000000000000000, mul(r0, z1))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    dd := mulmod(dd, nr, 0xffffffff00000001)
                }
                {
                    let r0 := 0
                    let r1 := 0
                    r0 := add(r0, add(mulmod(calldataload(add(ca, 3712)), add(mload(0x80), sub(0xffffffff00000001, calldataload(add(pu, 160)))), 0xffffffff00000001), mul(7, mulmod(calldataload(add(ca, 3744)), mload(0xa0), 0xffffffff00000001))))
                    r1 := add(r1, add(mulmod(calldataload(add(ca, 3712)), mload(0xa0), 0xffffffff00000001), mulmod(calldataload(add(ca, 3744)), add(mload(0x80), sub(0xffffffff00000001, calldataload(add(pu, 160)))), 0xffffffff00000001)))
                    r0 := mod(r0, 0xffffffff00000001)
                    r1 := mod(r1, 0xffffffff00000001)
                    let d0 := addmod(mload(0x2640), 2616409480461901825, 0xffffffff00000001)
                    let nr := mod(add(mul(d0, d0), sub(0xffffffff00000001, w7)), 0xffffffff00000001)
                    n0 := mod(add(mul(n0, nr), mul(mod(add(mul(r0, d0), sub(0xffffffff000000010000000000000000000, mul(7, mul(r1, z1)))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    n1 := mod(add(mul(n1, nr), mul(mod(add(mul(r1, d0), sub(0xffffffff000000010000000000000000000, mul(r0, z1))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    dd := mulmod(dd, nr, 0xffffffff00000001)
                }
                {
                    let r0 := 0
                    let r1 := 0
                    r0 := add(r0, add(mulmod(calldataload(add(ca, 3776)), add(mload(0x80), sub(0xffffffff00000001, calldataload(add(pu, 192)))), 0xffffffff00000001), mul(7, mulmod(calldataload(add(ca, 3808)), mload(0xa0), 0xffffffff00000001))))
                    r1 := add(r1, add(mulmod(calldataload(add(ca, 3776)), mload(0xa0), 0xffffffff00000001), mulmod(calldataload(add(ca, 3808)), add(mload(0x80), sub(0xffffffff00000001, calldataload(add(pu, 192)))), 0xffffffff00000001)))
                    r0 := mod(r0, 0xffffffff00000001)
                    r1 := mod(r1, 0xffffffff00000001)
                    let d0 := addmod(mload(0x2640), 1838090242242808025, 0xffffffff00000001)
                    let nr := mod(add(mul(d0, d0), sub(0xffffffff00000001, w7)), 0xffffffff00000001)
                    n0 := mod(add(mul(n0, nr), mul(mod(add(mul(r0, d0), sub(0xffffffff000000010000000000000000000, mul(7, mul(r1, z1)))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    n1 := mod(add(mul(n1, nr), mul(mod(add(mul(r1, d0), sub(0xffffffff000000010000000000000000000, mul(r0, z1))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    dd := mulmod(dd, nr, 0xffffffff00000001)
                }
                {
                    let r0 := 0
                    let r1 := 0
                    r0 := add(r0, add(mulmod(calldataload(add(ca, 3840)), add(mload(0x80), sub(0xffffffff00000001, calldataload(add(pu, 224)))), 0xffffffff00000001), mul(7, mulmod(calldataload(add(ca, 3872)), mload(0xa0), 0xffffffff00000001))))
                    r1 := add(r1, add(mulmod(calldataload(add(ca, 3840)), mload(0xa0), 0xffffffff00000001), mulmod(calldataload(add(ca, 3872)), add(mload(0x80), sub(0xffffffff00000001, calldataload(add(pu, 224)))), 0xffffffff00000001)))
                    r0 := mod(r0, 0xffffffff00000001)
                    r1 := mod(r1, 0xffffffff00000001)
                    let d0 := addmod(mload(0x2640), 16709414577370495860, 0xffffffff00000001)
                    let nr := mod(add(mul(d0, d0), sub(0xffffffff00000001, w7)), 0xffffffff00000001)
                    n0 := mod(add(mul(n0, nr), mul(mod(add(mul(r0, d0), sub(0xffffffff000000010000000000000000000, mul(7, mul(r1, z1)))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    n1 := mod(add(mul(n1, nr), mul(mod(add(mul(r1, d0), sub(0xffffffff000000010000000000000000000, mul(r0, z1))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    dd := mulmod(dd, nr, 0xffffffff00000001)
                }
                {
                    let r0 := 0
                    let r1 := 0
                    r0 := add(r0, add(mulmod(calldataload(add(ca, 3904)), add(mload(0x80), sub(0xffffffff00000001, calldataload(add(pu, 256)))), 0xffffffff00000001), mul(7, mulmod(calldataload(add(ca, 3936)), mload(0xa0), 0xffffffff00000001))))
                    r1 := add(r1, add(mulmod(calldataload(add(ca, 3904)), mload(0xa0), 0xffffffff00000001), mulmod(calldataload(add(ca, 3936)), add(mload(0x80), sub(0xffffffff00000001, calldataload(add(pu, 256)))), 0xffffffff00000001)))
                    r0 := mod(r0, 0xffffffff00000001)
                    r1 := mod(r1, 0xffffffff00000001)
                    let d0 := addmod(mload(0x2640), 10828172580964923874, 0xffffffff00000001)
                    let nr := mod(add(mul(d0, d0), sub(0xffffffff00000001, w7)), 0xffffffff00000001)
                    n0 := mod(add(mul(n0, nr), mul(mod(add(mul(r0, d0), sub(0xffffffff000000010000000000000000000, mul(7, mul(r1, z1)))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    n1 := mod(add(mul(n1, nr), mul(mod(add(mul(r1, d0), sub(0xffffffff000000010000000000000000000, mul(r0, z1))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    dd := mulmod(dd, nr, 0xffffffff00000001)
                }
                {
                    let r0 := 0
                    let r1 := 0
                    r0 := add(r0, add(mulmod(calldataload(add(ca, 3968)), add(mload(0x80), sub(0xffffffff00000001, calldataload(add(pu, 288)))), 0xffffffff00000001), mul(7, mulmod(calldataload(add(ca, 4000)), mload(0xa0), 0xffffffff00000001))))
                    r1 := add(r1, add(mulmod(calldataload(add(ca, 3968)), mload(0xa0), 0xffffffff00000001), mulmod(calldataload(add(ca, 4000)), add(mload(0x80), sub(0xffffffff00000001, calldataload(add(pu, 288)))), 0xffffffff00000001)))
                    r0 := mod(r0, 0xffffffff00000001)
                    r1 := mod(r1, 0xffffffff00000001)
                    let d0 := addmod(mload(0x2640), 11427738692958369984, 0xffffffff00000001)
                    let nr := mod(add(mul(d0, d0), sub(0xffffffff00000001, w7)), 0xffffffff00000001)
                    n0 := mod(add(mul(n0, nr), mul(mod(add(mul(r0, d0), sub(0xffffffff000000010000000000000000000, mul(7, mul(r1, z1)))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    n1 := mod(add(mul(n1, nr), mul(mod(add(mul(r1, d0), sub(0xffffffff000000010000000000000000000, mul(r0, z1))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    dd := mulmod(dd, nr, 0xffffffff00000001)
                }
                {
                    let r0 := 0
                    let r1 := 0
                    r0 := add(r0, add(mulmod(calldataload(add(ca, 4032)), add(mload(0x80), sub(0xffffffff00000001, calldataload(add(pu, 320)))), 0xffffffff00000001), mul(7, mulmod(calldataload(add(ca, 4064)), mload(0xa0), 0xffffffff00000001))))
                    r1 := add(r1, add(mulmod(calldataload(add(ca, 4032)), mload(0xa0), 0xffffffff00000001), mulmod(calldataload(add(ca, 4064)), add(mload(0x80), sub(0xffffffff00000001, calldataload(add(pu, 320)))), 0xffffffff00000001)))
                    r0 := mod(r0, 0xffffffff00000001)
                    r1 := mod(r1, 0xffffffff00000001)
                    let d0 := addmod(mload(0x2640), 13139551810201352472, 0xffffffff00000001)
                    let nr := mod(add(mul(d0, d0), sub(0xffffffff00000001, w7)), 0xffffffff00000001)
                    n0 := mod(add(mul(n0, nr), mul(mod(add(mul(r0, d0), sub(0xffffffff000000010000000000000000000, mul(7, mul(r1, z1)))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    n1 := mod(add(mul(n1, nr), mul(mod(add(mul(r1, d0), sub(0xffffffff000000010000000000000000000, mul(r0, z1))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    dd := mulmod(dd, nr, 0xffffffff00000001)
                }
                {
                    let r0 := 0
                    let r1 := 0
                    r0 := add(r0, add(mulmod(calldataload(add(ca, 4096)), add(mload(0x80), sub(0xffffffff00000001, calldataload(add(pu, 352)))), 0xffffffff00000001), mul(7, mulmod(calldataload(add(ca, 4128)), mload(0xa0), 0xffffffff00000001))))
                    r1 := add(r1, add(mulmod(calldataload(add(ca, 4096)), mload(0xa0), 0xffffffff00000001), mulmod(calldataload(add(ca, 4128)), add(mload(0x80), sub(0xffffffff00000001, calldataload(add(pu, 352)))), 0xffffffff00000001)))
                    r0 := mod(r0, 0xffffffff00000001)
                    r1 := mod(r1, 0xffffffff00000001)
                    let d0 := addmod(mload(0x2640), 10381269980041532680, 0xffffffff00000001)
                    let nr := mod(add(mul(d0, d0), sub(0xffffffff00000001, w7)), 0xffffffff00000001)
                    n0 := mod(add(mul(n0, nr), mul(mod(add(mul(r0, d0), sub(0xffffffff000000010000000000000000000, mul(7, mul(r1, z1)))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    n1 := mod(add(mul(n1, nr), mul(mod(add(mul(r1, d0), sub(0xffffffff000000010000000000000000000, mul(r0, z1))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    dd := mulmod(dd, nr, 0xffffffff00000001)
                }
                {
                    let r0 := 0
                    let r1 := 0
                    r0 := add(r0, add(mulmod(calldataload(add(ca, 4160)), add(mload(0x80), sub(0xffffffff00000001, calldataload(add(pu, 384)))), 0xffffffff00000001), mul(7, mulmod(calldataload(add(ca, 4192)), mload(0xa0), 0xffffffff00000001))))
                    r1 := add(r1, add(mulmod(calldataload(add(ca, 4160)), mload(0xa0), 0xffffffff00000001), mulmod(calldataload(add(ca, 4192)), add(mload(0x80), sub(0xffffffff00000001, calldataload(add(pu, 384)))), 0xffffffff00000001)))
                    r0 := mod(r0, 0xffffffff00000001)
                    r1 := mod(r1, 0xffffffff00000001)
                    let d0 := addmod(mload(0x2640), 2394121898621129512, 0xffffffff00000001)
                    let nr := mod(add(mul(d0, d0), sub(0xffffffff00000001, w7)), 0xffffffff00000001)
                    n0 := mod(add(mul(n0, nr), mul(mod(add(mul(r0, d0), sub(0xffffffff000000010000000000000000000, mul(7, mul(r1, z1)))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    n1 := mod(add(mul(n1, nr), mul(mod(add(mul(r1, d0), sub(0xffffffff000000010000000000000000000, mul(r0, z1))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    dd := mulmod(dd, nr, 0xffffffff00000001)
                }
                {
                    let r0 := 0
                    let r1 := 0
                    r0 := add(r0, add(mulmod(calldataload(add(ca, 4224)), add(mload(0x80), sub(0xffffffff00000001, calldataload(add(pu, 416)))), 0xffffffff00000001), mul(7, mulmod(calldataload(add(ca, 4256)), mload(0xa0), 0xffffffff00000001))))
                    r1 := add(r1, add(mulmod(calldataload(add(ca, 4224)), mload(0xa0), 0xffffffff00000001), mulmod(calldataload(add(ca, 4256)), add(mload(0x80), sub(0xffffffff00000001, calldataload(add(pu, 416)))), 0xffffffff00000001)))
                    r0 := mod(r0, 0xffffffff00000001)
                    r1 := mod(r1, 0xffffffff00000001)
                    let d0 := addmod(mload(0x2640), 13230089910221224091, 0xffffffff00000001)
                    let nr := mod(add(mul(d0, d0), sub(0xffffffff00000001, w7)), 0xffffffff00000001)
                    n0 := mod(add(mul(n0, nr), mul(mod(add(mul(r0, d0), sub(0xffffffff000000010000000000000000000, mul(7, mul(r1, z1)))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    n1 := mod(add(mul(n1, nr), mul(mod(add(mul(r1, d0), sub(0xffffffff000000010000000000000000000, mul(r0, z1))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    dd := mulmod(dd, nr, 0xffffffff00000001)
                }
                {
                    let r0 := 0
                    let r1 := 0
                    r0 := add(r0, add(mulmod(calldataload(add(ca, 4288)), add(mload(0x80), sub(0xffffffff00000001, calldataload(add(pu, 448)))), 0xffffffff00000001), mul(7, mulmod(calldataload(add(ca, 4320)), mload(0xa0), 0xffffffff00000001))))
                    r1 := add(r1, add(mulmod(calldataload(add(ca, 4288)), mload(0xa0), 0xffffffff00000001), mulmod(calldataload(add(ca, 4320)), add(mload(0x80), sub(0xffffffff00000001, calldataload(add(pu, 448)))), 0xffffffff00000001)))
                    r0 := mod(r0, 0xffffffff00000001)
                    r1 := mod(r1, 0xffffffff00000001)
                    let d0 := addmod(mload(0x2640), 4046825526400562279, 0xffffffff00000001)
                    let nr := mod(add(mul(d0, d0), sub(0xffffffff00000001, w7)), 0xffffffff00000001)
                    n0 := mod(add(mul(n0, nr), mul(mod(add(mul(r0, d0), sub(0xffffffff000000010000000000000000000, mul(7, mul(r1, z1)))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    n1 := mod(add(mul(n1, nr), mul(mod(add(mul(r1, d0), sub(0xffffffff000000010000000000000000000, mul(r0, z1))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    dd := mulmod(dd, nr, 0xffffffff00000001)
                }
                {
                    let r0 := 0
                    let r1 := 0
                    r0 := add(r0, add(mulmod(calldataload(add(ca, 4352)), add(mload(0x80), sub(0xffffffff00000001, calldataload(add(pu, 480)))), 0xffffffff00000001), mul(7, mulmod(calldataload(add(ca, 4384)), mload(0xa0), 0xffffffff00000001))))
                    r1 := add(r1, add(mulmod(calldataload(add(ca, 4352)), mload(0xa0), 0xffffffff00000001), mulmod(calldataload(add(ca, 4384)), add(mload(0x80), sub(0xffffffff00000001, calldataload(add(pu, 480)))), 0xffffffff00000001)))
                    r0 := mod(r0, 0xffffffff00000001)
                    r1 := mod(r1, 0xffffffff00000001)
                    let d0 := addmod(mload(0x2640), 5763753425300198500, 0xffffffff00000001)
                    let nr := mod(add(mul(d0, d0), sub(0xffffffff00000001, w7)), 0xffffffff00000001)
                    n0 := mod(add(mul(n0, nr), mul(mod(add(mul(r0, d0), sub(0xffffffff000000010000000000000000000, mul(7, mul(r1, z1)))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    n1 := mod(add(mul(n1, nr), mul(mod(add(mul(r1, d0), sub(0xffffffff000000010000000000000000000, mul(r0, z1))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    dd := mulmod(dd, nr, 0xffffffff00000001)
                }
                {
                    let r0 := 0
                    let r1 := 0
                    r0 := add(r0, add(mulmod(calldataload(add(ca, 4416)), add(mload(0x80), sub(0xffffffff00000001, calldataload(add(pu, 512)))), 0xffffffff00000001), mul(7, mulmod(calldataload(add(ca, 4448)), mload(0xa0), 0xffffffff00000001))))
                    r1 := add(r1, add(mulmod(calldataload(add(ca, 4416)), mload(0xa0), 0xffffffff00000001), mulmod(calldataload(add(ca, 4448)), add(mload(0x80), sub(0xffffffff00000001, calldataload(add(pu, 512)))), 0xffffffff00000001)))
                    r0 := mod(r0, 0xffffffff00000001)
                    r1 := mod(r1, 0xffffffff00000001)
                    let d0 := addmod(mload(0x2640), 16629639055023657349, 0xffffffff00000001)
                    let nr := mod(add(mul(d0, d0), sub(0xffffffff00000001, w7)), 0xffffffff00000001)
                    n0 := mod(add(mul(n0, nr), mul(mod(add(mul(r0, d0), sub(0xffffffff000000010000000000000000000, mul(7, mul(r1, z1)))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    n1 := mod(add(mul(n1, nr), mul(mod(add(mul(r1, d0), sub(0xffffffff000000010000000000000000000, mul(r0, z1))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    dd := mulmod(dd, nr, 0xffffffff00000001)
                }
                {
                    let r0 := 0
                    let r1 := 0
                    r0 := add(r0, add(mulmod(calldataload(add(ca, 4480)), add(mload(0x80), sub(0xffffffff00000001, calldataload(add(pu, 544)))), 0xffffffff00000001), mul(7, mulmod(calldataload(add(ca, 4512)), mload(0xa0), 0xffffffff00000001))))
                    r1 := add(r1, add(mulmod(calldataload(add(ca, 4480)), mload(0xa0), 0xffffffff00000001), mulmod(calldataload(add(ca, 4512)), add(mload(0x80), sub(0xffffffff00000001, calldataload(add(pu, 544)))), 0xffffffff00000001)))
                    r0 := mod(r0, 0xffffffff00000001)
                    r1 := mod(r1, 0xffffffff00000001)
                    let d0 := addmod(mload(0x2640), 2927035483026573067, 0xffffffff00000001)
                    let nr := mod(add(mul(d0, d0), sub(0xffffffff00000001, w7)), 0xffffffff00000001)
                    n0 := mod(add(mul(n0, nr), mul(mod(add(mul(r0, d0), sub(0xffffffff000000010000000000000000000, mul(7, mul(r1, z1)))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    n1 := mod(add(mul(n1, nr), mul(mod(add(mul(r1, d0), sub(0xffffffff000000010000000000000000000, mul(r0, z1))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    dd := mulmod(dd, nr, 0xffffffff00000001)
                }
                {
                    let r0 := 0
                    let r1 := 0
                    r0 := add(r0, add(mulmod(calldataload(add(ca, 4544)), add(mload(0x80), sub(0xffffffff00000001, calldataload(add(pu, 576)))), 0xffffffff00000001), mul(7, mulmod(calldataload(add(ca, 4576)), mload(0xa0), 0xffffffff00000001))))
                    r1 := add(r1, add(mulmod(calldataload(add(ca, 4544)), mload(0xa0), 0xffffffff00000001), mulmod(calldataload(add(ca, 4576)), add(mload(0x80), sub(0xffffffff00000001, calldataload(add(pu, 576)))), 0xffffffff00000001)))
                    r0 := mod(r0, 0xffffffff00000001)
                    r1 := mod(r1, 0xffffffff00000001)
                    let d0 := addmod(mload(0x2640), 1198782150536399688, 0xffffffff00000001)
                    let nr := mod(add(mul(d0, d0), sub(0xffffffff00000001, w7)), 0xffffffff00000001)
                    n0 := mod(add(mul(n0, nr), mul(mod(add(mul(r0, d0), sub(0xffffffff000000010000000000000000000, mul(7, mul(r1, z1)))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    n1 := mod(add(mul(n1, nr), mul(mod(add(mul(r1, d0), sub(0xffffffff000000010000000000000000000, mul(r0, z1))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    dd := mulmod(dd, nr, 0xffffffff00000001)
                }
                {
                    let r0 := 0
                    let r1 := 0
                    r0 := add(r0, add(mulmod(calldataload(add(ca, 4608)), add(mload(0x80), sub(0xffffffff00000001, calldataload(add(pu, 608)))), 0xffffffff00000001), mul(7, mulmod(calldataload(add(ca, 4640)), mload(0xa0), 0xffffffff00000001))))
                    r1 := add(r1, add(mulmod(calldataload(add(ca, 4608)), mload(0xa0), 0xffffffff00000001), mulmod(calldataload(add(ca, 4640)), add(mload(0x80), sub(0xffffffff00000001, calldataload(add(pu, 608)))), 0xffffffff00000001)))
                    r0 := mod(r0, 0xffffffff00000001)
                    r1 := mod(r1, 0xffffffff00000001)
                    let d0 := addmod(mload(0x2640), 348815134728872270, 0xffffffff00000001)
                    let nr := mod(add(mul(d0, d0), sub(0xffffffff00000001, w7)), 0xffffffff00000001)
                    n0 := mod(add(mul(n0, nr), mul(mod(add(mul(r0, d0), sub(0xffffffff000000010000000000000000000, mul(7, mul(r1, z1)))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    n1 := mod(add(mul(n1, nr), mul(mod(add(mul(r1, d0), sub(0xffffffff000000010000000000000000000, mul(r0, z1))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    dd := mulmod(dd, nr, 0xffffffff00000001)
                }
                {
                    let r0 := 0
                    let r1 := 0
                    r0 := add(r0, add(mulmod(calldataload(add(ca, 4672)), add(mload(0x80), sub(0xffffffff00000001, calldataload(add(pu, 640)))), 0xffffffff00000001), mul(7, mulmod(calldataload(add(ca, 4704)), mload(0xa0), 0xffffffff00000001))))
                    r1 := add(r1, add(mulmod(calldataload(add(ca, 4672)), mload(0xa0), 0xffffffff00000001), mulmod(calldataload(add(ca, 4704)), add(mload(0x80), sub(0xffffffff00000001, calldataload(add(pu, 640)))), 0xffffffff00000001)))
                    r0 := mod(r0, 0xffffffff00000001)
                    r1 := mod(r1, 0xffffffff00000001)
                    let d0 := addmod(mload(0x2640), 16016224591364643153, 0xffffffff00000001)
                    let nr := mod(add(mul(d0, d0), sub(0xffffffff00000001, w7)), 0xffffffff00000001)
                    n0 := mod(add(mul(n0, nr), mul(mod(add(mul(r0, d0), sub(0xffffffff000000010000000000000000000, mul(7, mul(r1, z1)))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    n1 := mod(add(mul(n1, nr), mul(mod(add(mul(r1, d0), sub(0xffffffff000000010000000000000000000, mul(r0, z1))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    dd := mulmod(dd, nr, 0xffffffff00000001)
                }
                {
                    let r0 := 0
                    let r1 := 0
                    r0 := add(r0, add(mulmod(calldataload(add(ca, 4736)), add(mload(0x80), sub(0xffffffff00000001, calldataload(add(pu, 672)))), 0xffffffff00000001), mul(7, mulmod(calldataload(add(ca, 4768)), mload(0xa0), 0xffffffff00000001))))
                    r1 := add(r1, add(mulmod(calldataload(add(ca, 4736)), mload(0xa0), 0xffffffff00000001), mulmod(calldataload(add(ca, 4768)), add(mload(0x80), sub(0xffffffff00000001, calldataload(add(pu, 672)))), 0xffffffff00000001)))
                    r0 := mod(r0, 0xffffffff00000001)
                    r1 := mod(r1, 0xffffffff00000001)
                    let d0 := addmod(mload(0x2640), 9458498463639030037, 0xffffffff00000001)
                    let nr := mod(add(mul(d0, d0), sub(0xffffffff00000001, w7)), 0xffffffff00000001)
                    n0 := mod(add(mul(n0, nr), mul(mod(add(mul(r0, d0), sub(0xffffffff000000010000000000000000000, mul(7, mul(r1, z1)))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    n1 := mod(add(mul(n1, nr), mul(mod(add(mul(r1, d0), sub(0xffffffff000000010000000000000000000, mul(r0, z1))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    dd := mulmod(dd, nr, 0xffffffff00000001)
                }
                {
                    let r0 := 0
                    let r1 := 0
                    r0 := add(r0, add(mulmod(calldataload(add(ca, 4800)), add(mload(0x80), sub(0xffffffff00000001, calldataload(add(pu, 704)))), 0xffffffff00000001), mul(7, mulmod(calldataload(add(ca, 4832)), mload(0xa0), 0xffffffff00000001))))
                    r1 := add(r1, add(mulmod(calldataload(add(ca, 4800)), mload(0xa0), 0xffffffff00000001), mulmod(calldataload(add(ca, 4832)), add(mload(0x80), sub(0xffffffff00000001, calldataload(add(pu, 704)))), 0xffffffff00000001)))
                    r0 := mod(r0, 0xffffffff00000001)
                    r1 := mod(r1, 0xffffffff00000001)
                    let d0 := addmod(mload(0x2640), 7539172197244716846, 0xffffffff00000001)
                    let nr := mod(add(mul(d0, d0), sub(0xffffffff00000001, w7)), 0xffffffff00000001)
                    n0 := mod(add(mul(n0, nr), mul(mod(add(mul(r0, d0), sub(0xffffffff000000010000000000000000000, mul(7, mul(r1, z1)))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    n1 := mod(add(mul(n1, nr), mul(mod(add(mul(r1, d0), sub(0xffffffff000000010000000000000000000, mul(r0, z1))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    dd := mulmod(dd, nr, 0xffffffff00000001)
                }
                {
                    let r0 := 0
                    let r1 := 0
                    r0 := add(r0, add(mulmod(calldataload(add(ca, 4864)), add(mload(0x80), sub(0xffffffff00000001, calldataload(add(pu, 736)))), 0xffffffff00000001), mul(7, mulmod(calldataload(add(ca, 4896)), mload(0xa0), 0xffffffff00000001))))
                    r1 := add(r1, add(mulmod(calldataload(add(ca, 4864)), mload(0xa0), 0xffffffff00000001), mulmod(calldataload(add(ca, 4896)), add(mload(0x80), sub(0xffffffff00000001, calldataload(add(pu, 736)))), 0xffffffff00000001)))
                    r0 := mod(r0, 0xffffffff00000001)
                    r1 := mod(r1, 0xffffffff00000001)
                    let d0 := addmod(mload(0x2640), 15405534276737706135, 0xffffffff00000001)
                    let nr := mod(add(mul(d0, d0), sub(0xffffffff00000001, w7)), 0xffffffff00000001)
                    n0 := mod(add(mul(n0, nr), mul(mod(add(mul(r0, d0), sub(0xffffffff000000010000000000000000000, mul(7, mul(r1, z1)))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    n1 := mod(add(mul(n1, nr), mul(mod(add(mul(r1, d0), sub(0xffffffff000000010000000000000000000, mul(r0, z1))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    dd := mulmod(dd, nr, 0xffffffff00000001)
                }
                {
                    let r0 := 0
                    let r1 := 0
                    r0 := add(r0, add(mulmod(calldataload(add(ca, 4928)), add(mload(0x80), sub(0xffffffff00000001, calldataload(add(pu, 768)))), 0xffffffff00000001), mul(7, mulmod(calldataload(add(ca, 4960)), mload(0xa0), 0xffffffff00000001))))
                    r1 := add(r1, add(mulmod(calldataload(add(ca, 4928)), mload(0xa0), 0xffffffff00000001), mulmod(calldataload(add(ca, 4960)), add(mload(0x80), sub(0xffffffff00000001, calldataload(add(pu, 768)))), 0xffffffff00000001)))
                    r0 := mod(r0, 0xffffffff00000001)
                    r1 := mod(r1, 0xffffffff00000001)
                    let d0 := addmod(mload(0x2640), 12232060331654591794, 0xffffffff00000001)
                    let nr := mod(add(mul(d0, d0), sub(0xffffffff00000001, w7)), 0xffffffff00000001)
                    n0 := mod(add(mul(n0, nr), mul(mod(add(mul(r0, d0), sub(0xffffffff000000010000000000000000000, mul(7, mul(r1, z1)))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    n1 := mod(add(mul(n1, nr), mul(mod(add(mul(r1, d0), sub(0xffffffff000000010000000000000000000, mul(r0, z1))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    dd := mulmod(dd, nr, 0xffffffff00000001)
                }
                {
                    let r0 := 0
                    let r1 := 0
                    r0 := add(r0, add(mulmod(calldataload(add(ca, 4992)), add(mload(0x80), sub(0xffffffff00000001, calldataload(add(pu, 800)))), 0xffffffff00000001), mul(7, mulmod(calldataload(add(ca, 5024)), mload(0xa0), 0xffffffff00000001))))
                    r1 := add(r1, add(mulmod(calldataload(add(ca, 4992)), mload(0xa0), 0xffffffff00000001), mulmod(calldataload(add(ca, 5024)), add(mload(0x80), sub(0xffffffff00000001, calldataload(add(pu, 800)))), 0xffffffff00000001)))
                    r0 := mod(r0, 0xffffffff00000001)
                    r1 := mod(r1, 0xffffffff00000001)
                    let d0 := addmod(mload(0x2640), 4839518232411412307, 0xffffffff00000001)
                    let nr := mod(add(mul(d0, d0), sub(0xffffffff00000001, w7)), 0xffffffff00000001)
                    n0 := mod(add(mul(n0, nr), mul(mod(add(mul(r0, d0), sub(0xffffffff000000010000000000000000000, mul(7, mul(r1, z1)))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    n1 := mod(add(mul(n1, nr), mul(mod(add(mul(r1, d0), sub(0xffffffff000000010000000000000000000, mul(r0, z1))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    dd := mulmod(dd, nr, 0xffffffff00000001)
                }
                {
                    let r0 := 0
                    let r1 := 0
                    r0 := add(r0, add(mulmod(calldataload(add(ca, 5056)), add(mload(0x80), sub(0xffffffff00000001, calldataload(add(pu, 832)))), 0xffffffff00000001), mul(7, mulmod(calldataload(add(ca, 5088)), mload(0xa0), 0xffffffff00000001))))
                    r1 := add(r1, add(mulmod(calldataload(add(ca, 5056)), mload(0xa0), 0xffffffff00000001), mulmod(calldataload(add(ca, 5088)), add(mload(0x80), sub(0xffffffff00000001, calldataload(add(pu, 832)))), 0xffffffff00000001)))
                    r0 := mod(r0, 0xffffffff00000001)
                    r1 := mod(r1, 0xffffffff00000001)
                    let d0 := addmod(mload(0x2640), 8036383496094416609, 0xffffffff00000001)
                    let nr := mod(add(mul(d0, d0), sub(0xffffffff00000001, w7)), 0xffffffff00000001)
                    n0 := mod(add(mul(n0, nr), mul(mod(add(mul(r0, d0), sub(0xffffffff000000010000000000000000000, mul(7, mul(r1, z1)))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    n1 := mod(add(mul(n1, nr), mul(mod(add(mul(r1, d0), sub(0xffffffff000000010000000000000000000, mul(r0, z1))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    dd := mulmod(dd, nr, 0xffffffff00000001)
                }
                {
                    let r0 := 0
                    let r1 := 0
                    r0 := add(r0, add(mulmod(calldataload(add(ca, 5120)), add(mload(0x80), sub(0xffffffff00000001, calldataload(add(pu, 864)))), 0xffffffff00000001), mul(7, mulmod(calldataload(add(ca, 5152)), mload(0xa0), 0xffffffff00000001))))
                    r1 := add(r1, add(mulmod(calldataload(add(ca, 5120)), mload(0xa0), 0xffffffff00000001), mulmod(calldataload(add(ca, 5152)), add(mload(0x80), sub(0xffffffff00000001, calldataload(add(pu, 864)))), 0xffffffff00000001)))
                    r0 := mod(r0, 0xffffffff00000001)
                    r1 := mod(r1, 0xffffffff00000001)
                    let d0 := addmod(mload(0x2640), 307471123441386853, 0xffffffff00000001)
                    let nr := mod(add(mul(d0, d0), sub(0xffffffff00000001, w7)), 0xffffffff00000001)
                    n0 := mod(add(mul(n0, nr), mul(mod(add(mul(r0, d0), sub(0xffffffff000000010000000000000000000, mul(7, mul(r1, z1)))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    n1 := mod(add(mul(n1, nr), mul(mod(add(mul(r1, d0), sub(0xffffffff000000010000000000000000000, mul(r0, z1))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    dd := mulmod(dd, nr, 0xffffffff00000001)
                }
                {
                    let r0 := 0
                    let r1 := 0
                    r0 := add(r0, add(mulmod(calldataload(add(ca, 5184)), add(mload(0x80), sub(0xffffffff00000001, calldataload(add(pu, 896)))), 0xffffffff00000001), mul(7, mulmod(calldataload(add(ca, 5216)), mload(0xa0), 0xffffffff00000001))))
                    r1 := add(r1, add(mulmod(calldataload(add(ca, 5184)), mload(0xa0), 0xffffffff00000001), mulmod(calldataload(add(ca, 5216)), add(mload(0x80), sub(0xffffffff00000001, calldataload(add(pu, 896)))), 0xffffffff00000001)))
                    r0 := mod(r0, 0xffffffff00000001)
                    r1 := mod(r1, 0xffffffff00000001)
                    let d0 := addmod(mload(0x2640), 7500740417092890225, 0xffffffff00000001)
                    let nr := mod(add(mul(d0, d0), sub(0xffffffff00000001, w7)), 0xffffffff00000001)
                    n0 := mod(add(mul(n0, nr), mul(mod(add(mul(r0, d0), sub(0xffffffff000000010000000000000000000, mul(7, mul(r1, z1)))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    n1 := mod(add(mul(n1, nr), mul(mod(add(mul(r1, d0), sub(0xffffffff000000010000000000000000000, mul(r0, z1))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    dd := mulmod(dd, nr, 0xffffffff00000001)
                }
                {
                    let r0 := 0
                    let r1 := 0
                    r0 := add(r0, add(mulmod(calldataload(add(ca, 5248)), add(mload(0x80), sub(0xffffffff00000001, calldataload(add(pu, 928)))), 0xffffffff00000001), mul(7, mulmod(calldataload(add(ca, 5280)), mload(0xa0), 0xffffffff00000001))))
                    r1 := add(r1, add(mulmod(calldataload(add(ca, 5248)), mload(0xa0), 0xffffffff00000001), mulmod(calldataload(add(ca, 5280)), add(mload(0x80), sub(0xffffffff00000001, calldataload(add(pu, 928)))), 0xffffffff00000001)))
                    r0 := mod(r0, 0xffffffff00000001)
                    r1 := mod(r1, 0xffffffff00000001)
                    let d0 := addmod(mload(0x2640), 4240954091795636346, 0xffffffff00000001)
                    let nr := mod(add(mul(d0, d0), sub(0xffffffff00000001, w7)), 0xffffffff00000001)
                    n0 := mod(add(mul(n0, nr), mul(mod(add(mul(r0, d0), sub(0xffffffff000000010000000000000000000, mul(7, mul(r1, z1)))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    n1 := mod(add(mul(n1, nr), mul(mod(add(mul(r1, d0), sub(0xffffffff000000010000000000000000000, mul(r0, z1))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    dd := mulmod(dd, nr, 0xffffffff00000001)
                }
                {
                    let r0 := 0
                    let r1 := 0
                    r0 := add(r0, add(mulmod(calldataload(add(ca, 5312)), add(mload(0x80), sub(0xffffffff00000001, calldataload(add(pu, 960)))), 0xffffffff00000001), mul(7, mulmod(calldataload(add(ca, 5344)), mload(0xa0), 0xffffffff00000001))))
                    r1 := add(r1, add(mulmod(calldataload(add(ca, 5312)), mload(0xa0), 0xffffffff00000001), mulmod(calldataload(add(ca, 5344)), add(mload(0x80), sub(0xffffffff00000001, calldataload(add(pu, 960)))), 0xffffffff00000001)))
                    r0 := mod(r0, 0xffffffff00000001)
                    r1 := mod(r1, 0xffffffff00000001)
                    let d0 := addmod(mload(0x2640), 8986540984031740934, 0xffffffff00000001)
                    let nr := mod(add(mul(d0, d0), sub(0xffffffff00000001, w7)), 0xffffffff00000001)
                    n0 := mod(add(mul(n0, nr), mul(mod(add(mul(r0, d0), sub(0xffffffff000000010000000000000000000, mul(7, mul(r1, z1)))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    n1 := mod(add(mul(n1, nr), mul(mod(add(mul(r1, d0), sub(0xffffffff000000010000000000000000000, mul(r0, z1))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    dd := mulmod(dd, nr, 0xffffffff00000001)
                }
                {
                    let r0 := 0
                    let r1 := 0
                    r0 := add(r0, add(mulmod(calldataload(add(ca, 5376)), add(mload(0x80), sub(0xffffffff00000001, calldataload(add(pu, 992)))), 0xffffffff00000001), mul(7, mulmod(calldataload(add(ca, 5408)), mload(0xa0), 0xffffffff00000001))))
                    r1 := add(r1, add(mulmod(calldataload(add(ca, 5376)), mload(0xa0), 0xffffffff00000001), mulmod(calldataload(add(ca, 5408)), add(mload(0x80), sub(0xffffffff00000001, calldataload(add(pu, 992)))), 0xffffffff00000001)))
                    r0 := mod(r0, 0xffffffff00000001)
                    r1 := mod(r1, 0xffffffff00000001)
                    let d0 := addmod(mload(0x2640), 327252734863309755, 0xffffffff00000001)
                    let nr := mod(add(mul(d0, d0), sub(0xffffffff00000001, w7)), 0xffffffff00000001)
                    n0 := mod(add(mul(n0, nr), mul(mod(add(mul(r0, d0), sub(0xffffffff000000010000000000000000000, mul(7, mul(r1, z1)))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    n1 := mod(add(mul(n1, nr), mul(mod(add(mul(r1, d0), sub(0xffffffff000000010000000000000000000, mul(r0, z1))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    dd := mulmod(dd, nr, 0xffffffff00000001)
                }
                {
                    let r0 := 0
                    let r1 := 0
                    r0 := add(r0, add(mulmod(calldataload(add(ca, 5440)), add(mload(0x80), sub(0xffffffff00000001, calldataload(add(pu, 1024)))), 0xffffffff00000001), mul(7, mulmod(calldataload(add(ca, 5472)), mload(0xa0), 0xffffffff00000001))))
                    r1 := add(r1, add(mulmod(calldataload(add(ca, 5440)), mload(0xa0), 0xffffffff00000001), mulmod(calldataload(add(ca, 5472)), add(mload(0x80), sub(0xffffffff00000001, calldataload(add(pu, 1024)))), 0xffffffff00000001)))
                    r0 := mod(r0, 0xffffffff00000001)
                    r1 := mod(r1, 0xffffffff00000001)
                    let d0 := addmod(mload(0x2640), 11639791320518665493, 0xffffffff00000001)
                    let nr := mod(add(mul(d0, d0), sub(0xffffffff00000001, w7)), 0xffffffff00000001)
                    n0 := mod(add(mul(n0, nr), mul(mod(add(mul(r0, d0), sub(0xffffffff000000010000000000000000000, mul(7, mul(r1, z1)))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    n1 := mod(add(mul(n1, nr), mul(mod(add(mul(r1, d0), sub(0xffffffff000000010000000000000000000, mul(r0, z1))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    dd := mulmod(dd, nr, 0xffffffff00000001)
                }
                {
                    let r0 := 0
                    let r1 := 0
                    r0 := add(r0, add(mulmod(calldataload(add(ca, 5504)), add(mload(0x80), sub(0xffffffff00000001, calldataload(add(pu, 1056)))), 0xffffffff00000001), mul(7, mulmod(calldataload(add(ca, 5536)), mload(0xa0), 0xffffffff00000001))))
                    r1 := add(r1, add(mulmod(calldataload(add(ca, 5504)), mload(0xa0), 0xffffffff00000001), mulmod(calldataload(add(ca, 5536)), add(mload(0x80), sub(0xffffffff00000001, calldataload(add(pu, 1056)))), 0xffffffff00000001)))
                    r0 := mod(r0, 0xffffffff00000001)
                    r1 := mod(r1, 0xffffffff00000001)
                    let d0 := addmod(mload(0x2640), 4177186796250661966, 0xffffffff00000001)
                    let nr := mod(add(mul(d0, d0), sub(0xffffffff00000001, w7)), 0xffffffff00000001)
                    n0 := mod(add(mul(n0, nr), mul(mod(add(mul(r0, d0), sub(0xffffffff000000010000000000000000000, mul(7, mul(r1, z1)))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    n1 := mod(add(mul(n1, nr), mul(mod(add(mul(r1, d0), sub(0xffffffff000000010000000000000000000, mul(r0, z1))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    dd := mulmod(dd, nr, 0xffffffff00000001)
                }
                {
                    let r0 := 0
                    let r1 := 0
                    r0 := add(r0, add(mulmod(calldataload(add(ca, 5568)), add(mload(0x80), sub(0xffffffff00000001, calldataload(add(pu, 1088)))), 0xffffffff00000001), mul(7, mulmod(calldataload(add(ca, 5600)), mload(0xa0), 0xffffffff00000001))))
                    r1 := add(r1, add(mulmod(calldataload(add(ca, 5568)), mload(0xa0), 0xffffffff00000001), mulmod(calldataload(add(ca, 5600)), add(mload(0x80), sub(0xffffffff00000001, calldataload(add(pu, 1088)))), 0xffffffff00000001)))
                    r0 := mod(r0, 0xffffffff00000001)
                    r1 := mod(r1, 0xffffffff00000001)
                    let d0 := addmod(mload(0x2640), 7125987021181317534, 0xffffffff00000001)
                    let nr := mod(add(mul(d0, d0), sub(0xffffffff00000001, w7)), 0xffffffff00000001)
                    n0 := mod(add(mul(n0, nr), mul(mod(add(mul(r0, d0), sub(0xffffffff000000010000000000000000000, mul(7, mul(r1, z1)))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    n1 := mod(add(mul(n1, nr), mul(mod(add(mul(r1, d0), sub(0xffffffff000000010000000000000000000, mul(r0, z1))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    dd := mulmod(dd, nr, 0xffffffff00000001)
                }
                {
                    let r0 := 0
                    let r1 := 0
                    r0 := add(r0, add(mulmod(calldataload(add(ca, 5632)), add(mload(0x80), sub(0xffffffff00000001, calldataload(add(pu, 1120)))), 0xffffffff00000001), mul(7, mulmod(calldataload(add(ca, 5664)), mload(0xa0), 0xffffffff00000001))))
                    r1 := add(r1, add(mulmod(calldataload(add(ca, 5632)), mload(0xa0), 0xffffffff00000001), mulmod(calldataload(add(ca, 5664)), add(mload(0x80), sub(0xffffffff00000001, calldataload(add(pu, 1120)))), 0xffffffff00000001)))
                    r0 := mod(r0, 0xffffffff00000001)
                    r1 := mod(r1, 0xffffffff00000001)
                    let d0 := addmod(mload(0x2640), 6731394197516204640, 0xffffffff00000001)
                    let nr := mod(add(mul(d0, d0), sub(0xffffffff00000001, w7)), 0xffffffff00000001)
                    n0 := mod(add(mul(n0, nr), mul(mod(add(mul(r0, d0), sub(0xffffffff000000010000000000000000000, mul(7, mul(r1, z1)))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    n1 := mod(add(mul(n1, nr), mul(mod(add(mul(r1, d0), sub(0xffffffff000000010000000000000000000, mul(r0, z1))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    dd := mulmod(dd, nr, 0xffffffff00000001)
                }
                {
                    let r0 := 0
                    let r1 := 0
                    r0 := add(r0, add(mulmod(calldataload(add(ca, 5824)), add(mload(0x900), 18446744069414584320), 0xffffffff00000001), mul(7, mulmod(calldataload(add(ca, 5856)), mload(0x920), 0xffffffff00000001))))
                    r1 := add(r1, add(mulmod(calldataload(add(ca, 5824)), mload(0x920), 0xffffffff00000001), mulmod(calldataload(add(ca, 5856)), add(mload(0x900), 18446744069414584320), 0xffffffff00000001)))
                    r0 := add(r0, add(mulmod(calldataload(add(ca, 5888)), add(mload(0x940), 0), 0xffffffff00000001), mul(7, mulmod(calldataload(add(ca, 5920)), mload(0x960), 0xffffffff00000001))))
                    r1 := add(r1, add(mulmod(calldataload(add(ca, 5888)), mload(0x960), 0xffffffff00000001), mulmod(calldataload(add(ca, 5920)), add(mload(0x940), 0), 0xffffffff00000001)))
                    r0 := add(r0, add(mulmod(calldataload(add(ca, 6080)), add(mload(0x980), 18446744069414584320), 0xffffffff00000001), mul(7, mulmod(calldataload(add(ca, 6112)), mload(0x9a0), 0xffffffff00000001))))
                    r1 := add(r1, add(mulmod(calldataload(add(ca, 6080)), mload(0x9a0), 0xffffffff00000001), mulmod(calldataload(add(ca, 6112)), add(mload(0x980), 18446744069414584320), 0xffffffff00000001)))
                    r0 := add(r0, add(mulmod(calldataload(add(ca, 6144)), add(mload(0x9c0), 0), 0xffffffff00000001), mul(7, mulmod(calldataload(add(ca, 6176)), mload(0x9e0), 0xffffffff00000001))))
                    r1 := add(r1, add(mulmod(calldataload(add(ca, 6144)), mload(0x9e0), 0xffffffff00000001), mulmod(calldataload(add(ca, 6176)), add(mload(0x9c0), 0), 0xffffffff00000001)))
                    r0 := add(r0, add(mulmod(calldataload(add(ca, 6336)), add(mload(0xa00), 18446744069414584320), 0xffffffff00000001), mul(7, mulmod(calldataload(add(ca, 6368)), mload(0xa20), 0xffffffff00000001))))
                    r1 := add(r1, add(mulmod(calldataload(add(ca, 6336)), mload(0xa20), 0xffffffff00000001), mulmod(calldataload(add(ca, 6368)), add(mload(0xa00), 18446744069414584320), 0xffffffff00000001)))
                    r0 := add(r0, add(mulmod(calldataload(add(ca, 6400)), add(mload(0xa40), 0), 0xffffffff00000001), mul(7, mulmod(calldataload(add(ca, 6432)), mload(0xa60), 0xffffffff00000001))))
                    r1 := add(r1, add(mulmod(calldataload(add(ca, 6400)), mload(0xa60), 0xffffffff00000001), mulmod(calldataload(add(ca, 6432)), add(mload(0xa40), 0), 0xffffffff00000001)))
                    r0 := add(r0, add(mulmod(calldataload(add(ca, 6592)), add(mload(0xa80), 18446744069414584320), 0xffffffff00000001), mul(7, mulmod(calldataload(add(ca, 6624)), mload(0xaa0), 0xffffffff00000001))))
                    r1 := add(r1, add(mulmod(calldataload(add(ca, 6592)), mload(0xaa0), 0xffffffff00000001), mulmod(calldataload(add(ca, 6624)), add(mload(0xa80), 18446744069414584320), 0xffffffff00000001)))
                    r0 := add(r0, add(mulmod(calldataload(add(ca, 6656)), add(mload(0xac0), 0), 0xffffffff00000001), mul(7, mulmod(calldataload(add(ca, 6688)), mload(0xae0), 0xffffffff00000001))))
                    r1 := add(r1, add(mulmod(calldataload(add(ca, 6656)), mload(0xae0), 0xffffffff00000001), mulmod(calldataload(add(ca, 6688)), add(mload(0xac0), 0), 0xffffffff00000001)))
                    r0 := mod(r0, 0xffffffff00000001)
                    r1 := mod(r1, 0xffffffff00000001)
                    let d0 := addmod(mload(0x2640), 837762896875133902, 0xffffffff00000001)
                    let nr := mod(add(mul(d0, d0), sub(0xffffffff00000001, w7)), 0xffffffff00000001)
                    n0 := mod(add(mul(n0, nr), mul(mod(add(mul(r0, d0), sub(0xffffffff000000010000000000000000000, mul(7, mul(r1, z1)))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    n1 := mod(add(mul(n1, nr), mul(mod(add(mul(r1, d0), sub(0xffffffff000000010000000000000000000, mul(r0, z1))), 0xffffffff00000001), dd)), 0xffffffff00000001)
                    dd := mulmod(dd, nr, 0xffffffff00000001)
                }
            }
            if iszero(eq(publics.length, 36)) {
                mstore(0, 0x8e4198e4)
                revert(0x1c, 4)
            }
            if iszero(and(and(eq(frame.length, 88), eq(periodic.length, 59)), eq(coeffs.length, 105))) {
                revert(0, 0)
            }
            calldatacopy(0x80, frame.offset, 5632)
            calldatacopy(0x1680, periodic.offset, 3776)
            mstore(0x2540, calldataload(add(point, 0)))
            mstore(0x2560, 0)
            mstore(0x2580, calldataload(add(point, 32)))
            mstore(0x25a0, 0)
            mstore(0x25c0, calldataload(add(point, 64)))
            mstore(0x25e0, 0)
            mstore(0x2600, calldataload(add(point, 96)))
            mstore(0x2620, 0)
            calldatacopy(0x2640, add(point, 128), 64)
            {
                let ok := 1
                ok := and(ok, lt(calldataload(add(publics.offset, 0)), 0xffffffff00000001))
                ok := and(ok, lt(calldataload(add(publics.offset, 32)), 0xffffffff00000001))
                ok := and(ok, lt(calldataload(add(publics.offset, 64)), 0xffffffff00000001))
                ok := and(ok, lt(calldataload(add(publics.offset, 96)), 0xffffffff00000001))
                ok := and(ok, lt(calldataload(add(publics.offset, 128)), 0xffffffff00000001))
                ok := and(ok, lt(calldataload(add(publics.offset, 160)), 0xffffffff00000001))
                ok := and(ok, lt(calldataload(add(publics.offset, 192)), 0xffffffff00000001))
                ok := and(ok, lt(calldataload(add(publics.offset, 224)), 0xffffffff00000001))
                ok := and(ok, lt(calldataload(add(publics.offset, 256)), 0xffffffff00000001))
                ok := and(ok, lt(calldataload(add(publics.offset, 288)), 0xffffffff00000001))
                ok := and(ok, lt(calldataload(add(publics.offset, 320)), 0xffffffff00000001))
                ok := and(ok, lt(calldataload(add(publics.offset, 352)), 0xffffffff00000001))
                ok := and(ok, lt(calldataload(add(publics.offset, 384)), 0xffffffff00000001))
                ok := and(ok, lt(calldataload(add(publics.offset, 416)), 0xffffffff00000001))
                ok := and(ok, lt(calldataload(add(publics.offset, 448)), 0xffffffff00000001))
                ok := and(ok, lt(calldataload(add(publics.offset, 480)), 0xffffffff00000001))
                ok := and(ok, lt(calldataload(add(publics.offset, 512)), 0xffffffff00000001))
                ok := and(ok, lt(calldataload(add(publics.offset, 544)), 0xffffffff00000001))
                ok := and(ok, lt(calldataload(add(publics.offset, 576)), 0xffffffff00000001))
                ok := and(ok, lt(calldataload(add(publics.offset, 608)), 0xffffffff00000001))
                ok := and(ok, lt(calldataload(add(publics.offset, 640)), 0xffffffff00000001))
                ok := and(ok, lt(calldataload(add(publics.offset, 672)), 0xffffffff00000001))
                ok := and(ok, lt(calldataload(add(publics.offset, 704)), 0xffffffff00000001))
                ok := and(ok, lt(calldataload(add(publics.offset, 736)), 0xffffffff00000001))
                ok := and(ok, lt(calldataload(add(publics.offset, 768)), 0xffffffff00000001))
                ok := and(ok, lt(calldataload(add(publics.offset, 800)), 0xffffffff00000001))
                ok := and(ok, lt(calldataload(add(publics.offset, 832)), 0xffffffff00000001))
                ok := and(ok, lt(calldataload(add(publics.offset, 864)), 0xffffffff00000001))
                ok := and(ok, lt(calldataload(add(publics.offset, 896)), 0xffffffff00000001))
                ok := and(ok, lt(calldataload(add(publics.offset, 928)), 0xffffffff00000001))
                ok := and(ok, lt(calldataload(add(publics.offset, 960)), 0xffffffff00000001))
                ok := and(ok, lt(calldataload(add(publics.offset, 992)), 0xffffffff00000001))
                ok := and(ok, lt(calldataload(add(publics.offset, 1024)), 0xffffffff00000001))
                ok := and(ok, lt(calldataload(add(publics.offset, 1056)), 0xffffffff00000001))
                ok := and(ok, lt(calldataload(add(publics.offset, 1088)), 0xffffffff00000001))
                ok := and(ok, lt(calldataload(add(publics.offset, 1120)), 0xffffffff00000001))
                if iszero(ok) {
                    mstore(0, 0x7ba9e47a)
                    revert(0x1c, 4)
                }
            }
            if iszero(staticcall(gas(), mload(0x49e0), 0x80, 18560, 0x2680, 8832)) {
                returndatacopy(0, 0, returndatasize())
                revert(0, returndatasize())
            }
            if iszero(staticcall(gas(), mload(0x4a00), 0x80, 18560, 0x2680, 8832)) {
                returndatacopy(0, 0, returndatasize())
                revert(0, returndatasize())
            }
            if iszero(staticcall(gas(), mload(0x4a20), 0x80, 18560, 0x2680, 8832)) {
                returndatacopy(0, 0, returndatasize())
                revert(0, returndatasize())
            }
            trans(coeffs.offset)
            let n0, n1, dd := bnd(coeffs.offset, publics.offset)
            {
                let h0 := mload(0x4940)
                let h1 := mload(0x4960)
                let u0, u1 := f2mul(n0, n1, h0, h1)
                let v0 := addmod(mulmod(mload(0x4900), dd, 0xffffffff00000001), u0, 0xffffffff00000001)
                let v1 := addmod(mulmod(mload(0x4920), dd, 0xffffffff00000001), u1, 0xffffffff00000001)
                let i0, i1 := f2inv(mulmod(h0, dd, 0xffffffff00000001), mulmod(h1, dd, 0xffffffff00000001))
                v0, v1 := f2mul(v0, v1, i0, i1)
                mstore(0, v0)
                mstore(32, v1)
                return(0, 64)
            }
        }
    }
}
