// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {Test} from "forge-std/Test.sol";
import {console2} from "forge-std/console2.sol";
import {PoseidonGoldilocks} from "../../contracts/shield/PoseidonGoldilocks.sol";
import {IPoseidonGoldilocks} from "../../contracts/shield/interfaces/IPoseidonGoldilocks.sol";
import {ShieldedPool} from "../../contracts/shield/ShieldedPool.sol";
import {AssociationSetRegistry} from "../../contracts/shield/AssociationSetRegistry.sol";
import {IStarkVerifier} from "../../contracts/shield/interfaces/IStarkVerifier.sol";
import {IAssociationSetRegistry} from "../../contracts/shield/interfaces/IAssociationSetRegistry.sol";
import {MockStarkVerifier} from "./mocks/MockStarkVerifier.sol";
import {MockPoseidonGoldilocks} from "./mocks/MockPoseidonGoldilocks.sol";

/// @dev The bytecode of spec/poseidon-fast, deployed as is.
function deployFast(bytes memory init) returns (address a) {
    assembly {
        a := create(0, add(init, 0x20), mload(init))
    }
}

/// @notice PoseidonGoldilocksFast, generated by script/tools/poseidon_fast/gen.py, against
///         PoseidonGoldilocks: the committed bytecode is the generator's output, the pinned vectors
///         hold, and every call the pool can make returns the same bytes or reverts with the same
///         data, including malformed calldata and non-canonical limbs.
contract PoseidonFastTest is Test {
    uint256 internal constant P = 0xFFFFFFFF00000001;
    string internal constant INITCODE = "spec/poseidon-fast/PoseidonGoldilocksFast.initcode.hex";
    string internal constant RUNTIME = "spec/poseidon-fast/PoseidonGoldilocksFast.runtime.hex";

    PoseidonGoldilocks internal std;
    IPoseidonGoldilocks internal fast;

    function _file(string memory path) internal view returns (bytes memory) {
        return vm.parseBytes(string.concat("0x", vm.readFile(path)));
    }

    function setUp() public {
        std = new PoseidonGoldilocks();
        address a = deployFast(_file(INITCODE));
        require(a != address(0), "the committed initcode does not deploy");
        fast = IPoseidonGoldilocks(a);
    }

    function pack(uint256 l0, uint256 l1, uint256 l2, uint256 l3) internal pure returns (bytes32) {
        return bytes32(l0 | (l1 << 64) | (l2 << 128) | (l3 << 192));
    }

    // ------------------------------------------------------------ provenance

    /// @notice The committed initcode and runtime are what the generator emits from
    ///         spec/poseidon-constants.json today.
    function test_theGeneratorReproducesTheCommittedBytecode() public {
        string[] memory cmd = new string[](4);
        cmd[0] = "python3";
        cmd[1] = "script/tools/poseidon_fast/gen.py";
        cmd[2] = "--print";
        cmd[3] = "initcode";
        assertEq(vm.ffi(cmd), _file(INITCODE), "initcode");
        cmd[3] = "runtime";
        assertEq(vm.ffi(cmd), _file(RUNTIME), "runtime");
    }

    function test_theDeployedCodeIsTheCommittedRuntime() public view {
        assertEq(address(fast).code, _file(RUNTIME));
        assertLe(address(fast).code.length, 24576);
    }

    // ------------------------------------------------------------ vectors

    /// @notice The vectors of spec/poseidon-constants.json and spec/launch-selftest.json.
    function test_theVectorsHold() public view {
        string memory j = vm.readFile("spec/poseidon-constants.json");
        uint256[] memory l = vm.parseJsonUintArray(j, ".kats[0].left");
        uint256[] memory r = vm.parseJsonUintArray(j, ".kats[0].right");
        uint256[] memory d = vm.parseJsonUintArray(j, ".kats[0].digest");
        assertEq(fast.hash2(pack(l[0], l[1], l[2], l[3]), pack(r[0], r[1], r[2], r[3])), pack(d[0], d[1], d[2], d[3]));
        uint256[] memory x = vm.parseJsonUintArray(j, ".kats[1].input");
        d = vm.parseJsonUintArray(j, ".kats[1].digest");
        assertEq(fast.hashFields(x), pack(d[0], d[1], d[2], d[3]));

        string memory st = vm.readFile("spec/launch-selftest.json");
        assertEq(
            fast.hash2(vm.parseJsonBytes32(st, ".hash2.left"), vm.parseJsonBytes32(st, ".hash2.right")),
            vm.parseJsonBytes32(st, ".hash2.expected")
        );
        assertEq(fast.hashFields(vm.parseJsonUintArray(st, ".hashFields.input")), vm.parseJsonBytes32(st, ".hashFields.expected"));
    }

    // ------------------------------------------------------------ construction

    function test_theConstructorRefusesValue() public {
        bytes memory init = _file(INITCODE);
        address a;
        vm.deal(address(this), 1);
        assembly {
            a := create(1, add(init, 0x20), mload(init))
        }
        assertEq(a, address(0));
    }

    /// @notice The constructor runs the pinned vectors through the permutation it deploys: one byte
    ///         of the matrix table changed and nothing is deployed.
    function test_theConstructorRefusesATableThatFailsItsVectors() public {
        bytes memory init = _file(INITCODE);
        // the runtime ends with the packed matrix columns, so its last byte is table
        uint256 last = _file(RUNTIME).length - 1;
        init[last] = bytes1(uint8(init[last]) ^ 0x01);
        assertEq(deployFast(init), address(0));
    }

    // ------------------------------------------------------------ differential

    function _same(bytes memory cd) internal view {
        (bool ok1, bytes memory r1) = address(std).staticcall(cd);
        (bool ok2, bytes memory r2) = address(fast).staticcall(cd);
        assertEq(ok1, ok2, "success differs");
        assertEq(r1, r2, "returndata differs");
    }

    function _limb(uint256 seed, uint256 i) internal pure returns (uint256 x) {
        x = uint256(keccak256(abi.encode(seed, i)));
        uint256 mode = x >> 248;
        x &= 0xFFFFFFFFFFFFFFFF;
        if (mode < 8) x = P - 1 - (x & 0xF); // just below p
        else if (mode < 10) x = P + (x & 0xF); // non-canonical
        else if (mode < 12) x = x & 0xF; // tiny
        else if (x >= P) x -= P;
    }

    /// @notice 2,000 fixed inputs per entry point, edges and about 2% non-canonical limbs.
    function test_differentialFixed() public view {
        for (uint256 s = 0; s < 2000; ++s) {
            bytes32 l = pack(_limb(s, 0), _limb(s, 1), _limb(s, 2), _limb(s, 3));
            bytes32 r = pack(_limb(s, 4), _limb(s, 5), _limb(s, 6), _limb(s, 7));
            _same(abi.encodeCall(IPoseidonGoldilocks.hash2, (l, r)));
            uint256[] memory f = new uint256[](4);
            for (uint256 i = 0; i < 4; ++i) {
                f[i] = _limb(s, 20 + i);
            }
            _same(abi.encodeCall(IPoseidonGoldilocks.hashFields, (f)));
        }
    }

    /// forge-config: default.fuzz.runs = 2000
    function testFuzz_hash2(bytes32 l, bytes32 r) public view {
        _same(abi.encodeCall(IPoseidonGoldilocks.hash2, (l, r)));
    }

    /// forge-config: default.fuzz.runs = 2000
    function testFuzz_hash2Canonical(uint64[8] memory x) public view {
        bytes32 l = pack(x[0] % P, x[1] % P, x[2] % P, x[3] % P);
        bytes32 r = pack(x[4] % P, x[5] % P, x[6] % P, x[7] % P);
        _same(abi.encodeCall(IPoseidonGoldilocks.hash2, (l, r)));
        assertEq(fast.hash2(l, r), std.hash2(l, r));
    }

    /// forge-config: default.fuzz.runs = 2000
    function testFuzz_hashFields(uint64[6] memory x, uint8 len, uint8 bad) public view {
        uint256 n = len % 7;
        uint256[] memory f = new uint256[](n);
        for (uint256 i = 0; i < n; ++i) {
            f[i] = uint256(x[i]) % P;
        }
        if (n > 0 && bad < 16) f[bad % n] = P + bad;
        _same(abi.encodeCall(IPoseidonGoldilocks.hashFields, (f)));
    }

    /// forge-config: default.fuzz.runs = 2000
    function testFuzz_hashFieldsCanonical(uint64[4] memory x) public view {
        uint256[] memory f = new uint256[](4);
        for (uint256 i = 0; i < 4; ++i) {
            f[i] = uint256(x[i]) % P;
        }
        _same(abi.encodeCall(IPoseidonGoldilocks.hashFields, (f)));
        assertEq(fast.hashFields(f), std.hashFields(f));
    }

    /// @notice Arbitrary calldata: malformed ABI, unknown selectors, short input.
    /// forge-config: default.fuzz.runs = 2000
    function testFuzz_rawCalldata(bytes calldata cd) public view {
        _same(cd);
    }

    /// forge-config: default.fuzz.runs = 2000
    function testFuzz_rawWithSelector(uint8 which, bytes calldata tail) public view {
        bytes4[3] memory sels = [
            IPoseidonGoldilocks.hash2.selector,
            IPoseidonGoldilocks.hashFields.selector,
            bytes4(keccak256("commitNote(uint256[11])"))
        ];
        _same(abi.encodePacked(sels[which % 3], tail));
    }

    function test_malformedCalls() public view {
        bytes4 sel = IPoseidonGoldilocks.hashFields.selector;
        _same(abi.encodePacked(sel));
        _same(abi.encodePacked(sel, uint256(32)));
        _same(abi.encodePacked(sel, uint256(32), uint256(4), uint256(1), uint256(2), uint256(3)));
        _same(abi.encodePacked(sel, uint256(1 << 64), uint256(4)));
        _same(abi.encodePacked(sel, uint256(32), uint256(1 << 64)));
        _same(abi.encodePacked(sel, uint256(64), uint256(0), uint256(4), uint256(1), uint256(2), uint256(3), uint256(4)));
        _same(abi.encodePacked(sel, uint256(32), uint256(4), uint256(1), uint256(2), uint256(3), uint256(4), uint256(9)));
        _same(abi.encodePacked(sel, type(uint256).max, uint256(4)));
        _same(abi.encodePacked(sel, uint256(32), uint256(4), uint256(P), uint256(2), uint256(3), uint256(4)));
        _same(abi.encodePacked(sel, uint256(32), uint256(3), uint256(P), uint256(2), uint256(3)));
        _same(abi.encodePacked(IPoseidonGoldilocks.hash2.selector, bytes32(0)));
        _same(abi.encodePacked(bytes4(keccak256("commitNote(uint256[11])")), new uint256[](11)));
        _same(hex"b30c0b");
        _same("");
        _same(hex"deadbeef");
    }

    function test_valueReverts() public {
        vm.deal(address(this), 2);
        bytes memory cd = abi.encodeCall(IPoseidonGoldilocks.hash2, (bytes32(0), bytes32(0)));
        (bool ok1,) = address(std).call{value: 1}(cd);
        (bool ok2,) = address(fast).call{value: 1}(cd);
        assertFalse(ok1);
        assertFalse(ok2);
    }

    function test_gasPerCall() public view {
        bytes memory c1 = abi.encodeCall(IPoseidonGoldilocks.hash2, (pack(1, 2, 3, 4), pack(5, 6, 7, 8)));
        uint256[] memory f = new uint256[](4);
        bytes memory c2 = abi.encodeCall(IPoseidonGoldilocks.hashFields, (f));
        _gas(address(std), c1);
        _gas(address(fast), c1);
        console2.log("hash2      standard / fast", _gas(address(std), c1), _gas(address(fast), c1));
        console2.log("hashFields standard / fast", _gas(address(std), c2), _gas(address(fast), c2));
    }

    function _gas(address h, bytes memory cd) internal view returns (uint256 used) {
        uint256 g = gasleft();
        (bool ok,) = h.staticcall(cd);
        used = g - gasleft();
        require(ok, "call failed");
    }
}

/// @notice The pool's own hasher self-test, with the launch vectors DeployShapes passes: it accepts the
///         fast hasher and refuses a hasher that does not reproduce them.
contract PoseidonFastPoolSelfTest is Test {
    function _selfTest() internal view returns (ShieldedPool.DeploymentSelfTest memory s) {
        string memory j = vm.readFile("spec/launch-selftest.json");
        s.hash2Left = vm.parseJsonBytes32(j, ".hash2.left");
        s.hash2Right = vm.parseJsonBytes32(j, ".hash2.right");
        s.hash2Expected = vm.parseJsonBytes32(j, ".hash2.expected");
        s.fieldsInput = vm.parseJsonUintArray(j, ".hashFields.input");
        s.fieldsExpected = vm.parseJsonBytes32(j, ".hashFields.expected");
        s.proof = hex"53454c4654455354";
        s.proofPublicInputs = new uint256[](12);
        s.noteValue = vm.parseJsonUint(j, ".noteVector.value");
        s.noteAssetId = uint64(vm.parseJsonUint(j, ".noteVector.assetId"));
        s.noteOwnerCommit = vm.parseJsonBytes32(j, ".noteVector.ownerCommit");
        s.noteCommitmentExpected = vm.parseJsonBytes32(j, ".noteVector.commitment");
    }

    function _pool(address hasher) internal returns (ShieldedPool) {
        return new ShieldedPool(
            address(0x5AFE),
            IStarkVerifier(address(new MockStarkVerifier())),
            IPoseidonGoldilocks(hasher),
            IAssociationSetRegistry(address(new AssociationSetRegistry())),
            address(0xFEE),
            25,
            25,
            1,
            12,
            _selfTest()
        );
    }

    function test_thePoolAcceptsTheFastHasher() public {
        address fast = deployFast(
            vm.parseBytes(string.concat("0x", vm.readFile("spec/poseidon-fast/PoseidonGoldilocksFast.initcode.hex")))
        );
        ShieldedPool pool = _pool(fast);
        assertEq(address(pool.treeHasher()), fast);
    }

    function test_thePoolRefusesAHasherThatFailsTheVectors() public {
        address wrong = address(new MockPoseidonGoldilocks());
        ShieldedPool.DeploymentSelfTest memory st = _selfTest();
        IStarkVerifier v = IStarkVerifier(address(new MockStarkVerifier()));
        IAssociationSetRegistry reg = IAssociationSetRegistry(address(new AssociationSetRegistry()));
        vm.expectRevert(ShieldedPool.HasherSelfTestFailed.selector);
        new ShieldedPool(
            address(0x5AFE),
            v,
            IPoseidonGoldilocks(wrong),
            reg,
            address(0xFEE),
            25,
            25,
            1,
            12,
            st
        );
    }
}
