// SPDX-License-Identifier: MIT
// Generated by the verifier generator for this circuit and shape. Do not edit.
pragma solidity ^0.8.24;

import {StarkFieldExt as F} from "../StarkFieldExt.sol";
import {StarkTranscript as TS} from "../StarkTranscript.sol";
import {RealQueryVerify as V} from "../RealQueryVerify.sol";
import {RealQueryWalk as W} from "../RealQueryWalk.sol";
import {IProgramFormEvaluator} from "../IProgramFormEvaluator.sol";

/// @title PrepareNb_B
/// @notice The verifier's head, claims and transcripts for shape B (17 queries,
///         8 chunks of 30 bits), radix 8, 32-byte digests.
///         From the launch prepare: the
///         head, the claims, the main transcript, comp_z from the evaluator, the FRI transcript and
///         grinding, the DEEP preparation, then the final layer at every FRI position.
/// @dev The steps and refusals of RealQueryWalk.readHead, readClaims and RealQueryVerify's two
///      transcripts, in their order, with three changes that keep every value and every revert:
///      field limbs are decoded four per word; the transcripts absorb the frame, the claims and the
///      final layer from their wire bytes, which are their preimage bytes (StarkTranscript.
///      absorbFpWire); the final layer of the launch shape is decoded to a fixed address, where
///      Horner runs on constant addresses. Returns 366 words, laid out as gen.py's O_*.
contract PrepareNb_B {
    error NoEvaluator();
    error ClaimsNotTheDeployment();
    error FriShapeNotTheDeployment(uint256 roots, uint256 finalCount);
    error RegionWidthMismatch(uint256 declared, uint256 expected);
    error OodFrameMismatch(uint256 cells);
    error PeriodicCountMismatch(uint256 claimed);
    error HeadTrailingBytes();
    error MaskSlotNotZero(uint256 row);
    error FinalGrindRejected(uint256 search);
    error DeepGrindRejected();
    error QueryCountMismatch(uint256 count);
    error ShapeNotAccepted(uint256 id);
    error RowWidthMismatch(uint256 width);

    struct S {
        V.Head h;
        F.Fp2[] ood;
        V.Checkpoint ck;
        F.Fp2[] coeffs;
        uint256 cz0;
        uint256 cz1;
        F.Fp2[] betas;
        uint256[] friIdx;
        W.Base b;
        uint64 deepNonce;
    }

    /// @notice RealSplitVerifier.shape() of the launch deployment.
    function shape() public pure returns (V.Shape memory) {
        return V.Shape(
            17, 23, 13, 44, 106, 30, 7, 59,
            0x898b800f60f467f04ac9140fb425cd54181e4d1642f61fc38b5965d08ace2888,
            2, 34, 32, 8, true, true, true, true, false, 21, 8, 42
        );
    }

    /// @notice The shape id this prepare binds under 0x0A before the query grind (docs/16).
    function shapeId() external pure returns (uint256) {
        return 3;
    }

    function prepare(
        bytes calldata head,
        bytes calldata claims,
        uint256[] calldata publics,
        IProgramFormEvaluator ev
    ) external view {
        // [0x80, 0x40a0) holds the launch shape's final layer; nothing else lands there
        assembly {
            mstore(0x40, 0x40a0)
        }
        if (address(ev) == address(0)) revert NoEvaluator();
        if (claims.length == 0) revert ClaimsNotTheDeployment();
        S memory s;


        (s.h, s.ood) = _readHead(head);
        // RealSplitVerifier._friShape at 4^4 * 512 = 2^17
        if (s.h.finalCount != 256 || s.h.friRoots.length != 3) {
            revert FriShapeNotTheDeployment(s.h.friRoots.length, s.h.finalCount);
        }
        (s.h.periodicZ, s.deepNonce) = _readClaims(claims);

        (s.ck, s.coeffs) = _mainCheckpoint(s.h, s.ood, head, claims, publics);

        (s.cz0, s.cz1) = _evaluate(ev, s, publics);

        bytes32 seed;
        (s.coeffs, seed) = _deep(s.ck.state, s.deepNonce);
        (s.betas, s.friIdx) = _friChallenges(s.h, head, seed);

        s.b.traceWidth = 44;
        s.b.nPeriodic = 59;
        W.prepareDeep(s.b, s.ood, s.coeffs, s.h.periodicZ, s.cz0, s.cz1);

        _out(s);
    }

    // ------------------------------------------------------------------ decoding, as RealQueryWalk

    function _readHead(bytes calldata p) private pure returns (V.Head memory h, F.Fp2[] memory ood) {
        uint256 o;
        (h.permRoot, o) = _digest(p, 0);
        uint256 rw = _u32(p, o);
        o += 4;
        if (rw != 34) revert RegionWidthMismatch(rw, 34);
        (h.traceRoot, o) = _digest(p, o);
        (h.compRoot, o) = _digest(p, o);
        uint256 oodN = _u32(p, o);
        o += 4;
        if (oodN != 88) revert OodFrameMismatch(oodN);
        (ood, o) = _fp2s(p, o, 88);
        o = _roots(p, o, h);
        o = _finalLayer(p, o, h);
        uint256 n = _u32(p, o);
        o += 4;
        if (n != 17) revert QueryCountMismatch(n);
        o = _nonces(p, o, h);
        n = _u32(p, o);
        o += 4;
        if (n != 44) revert RowWidthMismatch(n);
        h.periodicZ = new F.Fp2[](0);
        if (o != p.length) revert HeadTrailingBytes();
    }

    function _readClaims(bytes calldata p) private pure returns (F.Fp2[] memory periodicZ, uint64 deepNonce) {
        uint256 np = _u32(p, 0);
        if (np != 59) revert PeriodicCountMismatch(np);
        uint256 o;
        (periodicZ, o) = _fp2s(p, 4, 59);
        uint64[] memory dn;
        (dn, o) = _u64s(p, o, 1);
        deepNonce = dn[0];
        if (o != p.length) revert HeadTrailingBytes();
    }

    function _digest(bytes calldata p, uint256 o) private pure returns (bytes32 d, uint256 next) {
        next = o + 32;
        if (next > p.length) _oob();
        assembly {
            d := calldataload(add(p.offset, o))
        }
    }

    function _u32(bytes calldata p, uint256 off) private pure returns (uint256 v) {
        if (off + 4 > p.length) _oob();
        assembly {
            v := shr(224, calldataload(add(p.offset, off)))
            v := or(shr(8, and(v, 0xFF00FF00)), shl(8, and(v, 0x00FF00FF)))
            v := or(shr(16, v), and(shl(16, v), 0xFFFF0000))
        }
    }

    function _oob() private pure {
        assembly {
            mstore(0x00, shl(224, 0xb4120f14))
            revert(0x00, 0x04)
        }
    }

    function _roots(bytes calldata p, uint256 o, V.Head memory h) private pure returns (uint256) {
        uint256 rc = _u32(p, o);
        o += 4;
        if (o + rc * 32 > p.length) _oob();
        h.friRoots = new bytes32[](rc);
        for (uint256 m = 0; m < rc; ++m) (h.friRoots[m], o) = _digest(p, o);
        return o;
    }

    // The launch shape's 256 cells into the fixed array at 0x80, four limbs a word.
    // Any other count takes RealQueryWalk.readFpFlat, and the shape check refuses it after the head.
    function _finalLayer(bytes calldata p, uint256 o, V.Head memory h) private pure returns (uint256) {
        uint256 fc = _u32(p, o);
        o += 4;
        h.finalCount = fc;
        uint256[] memory flat;
        if (fc == 256) {
            if (o + 4096 > p.length) _oob();
            assembly {
                flat := 0x80
                mstore(flat, 512)
                let src := add(p.offset, o)
                let m8 := 0xff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff
                let m16 := 0xffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff
                let m32 := 0xffffffff00000000ffffffff00000000ffffffff00000000ffffffff
                let bad := 0
                for { let i := 0 } lt(i, 4096) { i := add(i, 32) } {
                    let v := calldataload(add(src, i))
                    v := or(and(shr(8, v), m8), shl(8, and(v, m8)))
                    v := or(and(shr(16, v), m16), shl(16, and(v, m16)))
                    v := or(and(shr(32, v), m32), shl(32, and(v, m32)))
                    let a := shr(192, v)
                    let b := shr(192, shl(64, v))
                    let c := shr(192, shl(128, v))
                    v := shr(192, shl(192, v))
                    let d := add(0xa0, shl(2, i))
                    mstore(d, a)
                    mstore(add(d, 0x20), b)
                    mstore(add(d, 0x40), c)
                    mstore(add(d, 0x60), v)
                    bad := or(bad, or(or(add(a, 0xffffffff), add(b, 0xffffffff)), or(add(c, 0xffffffff), add(v, 0xffffffff))))
                }
                bad := shr(64, bad)
                if bad { mstore(0x00, shl(224, 0x459d1ca5)) revert(0x00, 0x04) }
            }
            o += 4096;
        } else {
            (flat, o) = W.readFpFlat(p, o, 2 * fc);
        }
        h.finalFlat = flat;
        if (fc == 0) {
            assembly {
                mstore(0x00, shl(224, 0x4e487b71))
                mstore(0x04, 0x32)
                revert(0x00, 0x24)
            }
        }
        h.finalValue = F.Fp2(flat[0], flat[1]);
        return o;
    }

    // The query nonces, then one per FRI root, as RealQueryWalk._nonces with QUERY_NONCES_FIRST.
    function _nonces(bytes calldata p, uint256 o, V.Head memory h) private pure returns (uint256) {
        uint256 rounds = h.friRoots.length;
        if (o + (8 + rounds) * 8 > p.length) _oob();
        (h.finalNonces, o) = _u64s(p, o, 8);
        (h.roundNonces, o) = _u64s(p, o, rounds);
        return o;
    }

    function _u64s(bytes calldata p, uint256 o, uint256 n) private pure returns (uint64[] memory out, uint256 next) {
        out = new uint64[](n);
        for (uint256 i = 0; i < n; ++i) {
            uint256 v;
            assembly {
                v := shr(192, calldataload(add(p.offset, o)))
                v := or(shr(8, and(v, 0xFF00FF00FF00FF00)), shl(8, and(v, 0x00FF00FF00FF00FF)))
                v := or(shr(16, and(v, 0xFFFF0000FFFF0000)), shl(16, and(v, 0x0000FFFF0000FFFF)))
                v := or(shr(32, v), and(shl(32, v), 0xFFFFFFFF00000000))
            }
            out[i] = uint64(v);
            o += 8;
        }
        next = o;
    }

    // RealQueryWalk.readFp2Array, two cells a word: OutOfBounds before anything is read,
    // NonCanonicalFp once all are decoded.
    function _fp2s(bytes calldata p, uint256 o, uint256 n) private pure returns (F.Fp2[] memory out, uint256 next) {
        next = o + n * 16;
        if (next > p.length) _oob();
        assembly {
            out := mload(0x40)
            mstore(out, n)
            let ptr := add(out, 0x20)
            let cell := add(ptr, mul(n, 0x20))
            mstore(0x40, add(cell, mul(n, 0x40)))
            let src := add(p.offset, o)
                let m8 := 0xff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff
                let m16 := 0xffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff
                let m32 := 0xffffffff00000000ffffffff00000000ffffffff00000000ffffffff
                let bad := 0
                let fin := add(cell, mul(n, 0x40))
                for {} lt(cell, fin) {} {
                    let v := calldataload(src)
                    v := or(and(shr(8, v), m8), shl(8, and(v, m8)))
                    v := or(and(shr(16, v), m16), shl(16, and(v, m16)))
                    v := or(and(shr(32, v), m32), shl(32, and(v, m32)))
                    let a := shr(192, v)
                    let b := shr(192, shl(64, v))
                    mstore(ptr, cell)
                    mstore(cell, a)
                    mstore(add(cell, 0x20), b)
                    bad := or(bad, or(add(a, 0xffffffff), add(b, 0xffffffff)))
                    cell := add(cell, 0x40)
                    ptr := add(ptr, 0x20)
                    if lt(cell, fin) {
                        a := shr(192, shl(128, v))
                        b := shr(192, shl(192, v))
                        mstore(ptr, cell)
                        mstore(cell, a)
                        mstore(add(cell, 0x20), b)
                        bad := or(bad, or(add(a, 0xffffffff), add(b, 0xffffffff)))
                        cell := add(cell, 0x40)
                        ptr := add(ptr, 0x20)
                    }
                    src := add(src, 32)
                }
                bad := shr(64, bad)
            if bad {
                mstore(0x00, shl(224, 0x459d1ca5))
                revert(0x00, 0x04)
            }
        }
    }

    // ------------------------------------------------------------------ transcripts, as RealQueryVerify

    // One absorb per vector, state = keccak256(0x02 || state || all its limbs' bytes).
    function _bulkWire(TS.T memory t, bytes calldata p, uint256 off, uint256 n) private pure {
        assembly {
            let pre := mload(0x40)
            mstore8(pre, 0x02)
            mstore(add(pre, 1), mload(t))
            calldatacopy(add(pre, 33), add(p.offset, off), mul(n, 8))
            mstore(t, keccak256(pre, add(33, mul(n, 8))))
        }
    }

    function _bulkArr(TS.T memory t, uint256[] memory a) private pure {
        assembly {
            let pre := mload(0x40)
            mstore8(pre, 0x02)
            mstore(add(pre, 1), mload(t))
            let n := mload(a)
            let dst := add(pre, 33)
            let src := add(a, 0x20)
            for { let i := 0 } lt(i, n) { i := add(i, 1) } {
                let w := and(mload(add(src, shl(5, i))), 0xFFFFFFFFFFFFFFFF)
                w := or(shr(8, and(w, 0xFF00FF00FF00FF00)), shl(8, and(w, 0x00FF00FF00FF00FF)))
                w := or(shr(16, and(w, 0xFFFF0000FFFF0000)), shl(16, and(w, 0x0000FFFF0000FFFF)))
                w := or(shr(32, w), and(shl(32, w), 0xFFFFFFFF00000000))
                mstore(add(dst, shl(3, i)), shl(192, w))
            }
            mstore(t, keccak256(pre, add(33, shl(3, n))))
        }
    }


    // _mainCheckpoint with keep, for the launch codec. The frame and the claims are absorbed from
    // their wire bytes: the same preimages as absorbFp2Array over the decoded cells.
    function _mainCheckpoint(
        V.Head memory h,
        F.Fp2[] memory ood,
        bytes calldata head,
        bytes calldata claims,
        uint256[] memory publics
    ) private pure returns (V.Checkpoint memory c, F.Fp2[] memory coeffs) {
        TS.T memory t = TS.init("NONOS-STARK-EXT");
        _bulkArr(t, publics);
        TS.absorbDigest(t, h.traceRoot, 32);
        c.beta = _draw2(t);
        c.gamma = _draw2(t);
        TS.absorbDigest(t, h.permRoot, 32);
        F.Fp2 memory alpha = _draw2(t);
        coeffs = TS.powers(alpha, 106);
        TS.absorbDigest(t, h.compRoot, 32);
        c.z = _draw2(t);
        for (uint256 k = 0; k < 2; ++k) {
            F.Fp2 memory v = ood[k * 44 + 43];
            if (v.c0 != 0 || v.c1 != 0) revert MaskSlotNotZero(k);
        }
        _bulkWire(t, head, 104, 176);
        _bulkWire(t, claims, 4, 118);

        c.state = t.state;
    }

    // friChallenges for the launch codec, the final layer absorbed from its wire bytes.
    function _friChallenges(V.Head memory h, bytes calldata head, bytes32 seed)
        private
        pure
        returns (F.Fp2[] memory betas, uint256[] memory friIdx)
    {
        TS.T memory tf = TS.init("NONOS-STARK-FRI-EXT");
        TS.absorbDigest(tf, seed, 32);
        betas = new F.Fp2[](3);
        TS.absorbDigest(tf, h.friRoots[0], 32);
        TS.grindRound(tf, h.roundNonces[0], 21, 0);
        betas[0] = _draw2(tf);
        TS.absorbDigest(tf, h.friRoots[1], 32);
        TS.grindRound(tf, h.roundNonces[1], 21, 1);
        betas[1] = _draw2(tf);
        TS.absorbDigest(tf, h.friRoots[2], 32);
        TS.grindRound(tf, h.roundNonces[2], 21, 2);
        betas[2] = _draw2(tf);
        _bulkWire(tf, head, 1616, 512);

        _bindShape(tf);
        for (uint256 i = 0; i < 8; ++i) {
            if (!TS.verifyPow(tf, h.finalNonces[i], 30)) revert FinalGrindRejected(i);
        }
        friIdx = new uint256[](17);
        for (uint256 i = 0; i < 17; ++i) {
            friIdx[i] = TS.challengeIndex(tf, 8388608);
        }
    }

    // docs/15: an F_p^2 challenge is the first two accepted lanes of one stream under 0x06. A lane is
    // state[8j .. 8j + 8] little-endian, accepted iff it is below p; a spent squeeze is refilled.
    function _draw2(TS.T memory t) private pure returns (F.Fp2 memory r) {
        uint256 c0;
        uint256 c1;
        assembly {
            let pre := mload(0x40)
            let s := mload(t)
            let got := 0
            for {} lt(got, 2) {} {
                mstore8(pre, 0x6)
                mstore(add(pre, 1), s)
                s := keccak256(pre, 33)
                let v := s
                v := or(shr(8, and(v, 0xff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00)), shl(8, and(v, 0xff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff)))
                v := or(shr(16, and(v, 0xffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000)), shl(16, and(v, 0xffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff)))
                v := or(shr(32, and(v, 0xffffffff00000000ffffffff00000000ffffffff00000000ffffffff00000000)), shl(32, and(v, 0xffffffff00000000ffffffff00000000ffffffff00000000ffffffff)))
                for { let sh := 192 } 1 { sh := sub(sh, 64) } {
                    let w := and(shr(sh, v), 0xffffffffffffffff)
                    if lt(w, 0xffffffff00000001) {
                        switch got
                        case 0 { c0 := w }
                        default { c1 := w }
                        got := add(got, 1)
                        if eq(got, 2) { break }
                    }
                    if iszero(sh) { break }
                }
            }
            mstore(t, s)
        }
        r = F.Fp2(c0, c1);
    }

    // The DEEP round (docs/15): a 19-bit grind under the query grind's rule, its nonce
    // absorbed on success, then 148 independent F_p^2 coefficients as one stream under
    // 0x9, in the launch's coefficient order. Then the FRI seed, as the launch draws it.
    function _deep(bytes32 state, uint64 nonce) private view returns (F.Fp2[] memory d, bytes32 seed) {
        TS.T memory t = TS.T(state);
        if (!TS.verifyPow(t, nonce, 19)) revert DeepGrindRejected();
        assembly {
            d := mload(0x40)
            mstore(d, 148)
            let ptr := add(d, 0x20)
            let cell := add(ptr, 0x1280)
            let end := add(cell, 0x2500)
            mstore(0x40, end)
            for { let c := cell } lt(c, end) { c := add(c, 0x40) } {
                mstore(ptr, c)
                ptr := add(ptr, 0x20)
            }
            let pre := end
            let s := mload(t)
            for {} lt(cell, end) {} {
                mstore8(pre, 0x9)
                mstore(add(pre, 1), s)
                s := keccak256(pre, 33)
                let v := s
                v := or(shr(8, and(v, 0xff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00)), shl(8, and(v, 0xff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff)))
                v := or(shr(16, and(v, 0xffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000)), shl(16, and(v, 0xffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff)))
                v := or(shr(32, and(v, 0xffffffff00000000ffffffff00000000ffffffff00000000ffffffff00000000)), shl(32, and(v, 0xffffffff00000000ffffffff00000000ffffffff00000000ffffffff)))
                for { let sh := 192 } 1 { sh := sub(sh, 64) } {
                    let w := and(shr(sh, v), 0xffffffffffffffff)
                    if lt(w, 0xffffffff00000001) {
                        mstore(cell, w)
                        cell := add(cell, 0x20)
                        if eq(cell, end) { break }
                    }
                    if iszero(sh) { break }
                }
            }
            mstore(t, s)
        }

        // With the mask pair opened as N = M_c + X M_{c+1}, the second column's coefficient is the
        // first's times X (RealQueryVerify._deepCoeffs).
        for (uint256 k = 0; k < 2; ++k) {
            uint256 i = k * 44 + 42;
            d[i + 1] = F.Fp2(mulmod(7, d[i].c1, F.P), d[i].c0);
        }
        TS.mix(t, 0x8, "");
        seed = t.state;
    }

    // docs/16: the shape bound before any query grind, state = keccak256(0x0A || state || id).
    function _bindShape(TS.T memory t) private pure {
        assembly {
            let pre := mload(0x40)
            mstore8(pre, 0xa)
            mstore(add(pre, 1), mload(t))
            mstore8(add(pre, 33), 0x3)
            mstore(t, keccak256(pre, 34))
        }
    }

    function _evaluate(IProgramFormEvaluator ev, S memory s, uint256[] calldata publics)
        private
        view
        returns (uint256, uint256)
    {
        uint256[2][] memory fr;
        uint256[2][] memory pz;
        uint256[2][] memory cf;
        F.Fp2[] memory ood = s.ood;
        F.Fp2[] memory per = s.h.periodicZ;
        F.Fp2[] memory co = s.coeffs;
        assembly {
            fr := ood
            pz := per
            cf := co
        }
        V.Checkpoint memory ck = s.ck;
        return ev.evaluate(fr, pz, cf, publics, [ck.beta.c0, ck.beta.c1, ck.gamma.c0, ck.gamma.c1, ck.z.c0, ck.z.c1]);
    }

    // ------------------------------------------------------------------ output

    function _out(S memory s) private view {
        V.Head memory h = s.h;
        bytes32[] memory roots = h.friRoots;
        F.Fp2[] memory betas = s.betas;
        uint256[] memory idx = s.friIdx;
        W.Base memory b = s.b;
        uint256[] memory kf = b.kflat;
        F.Fp2 memory z = s.ck.z;
        assembly {
            let o := mload(0x40)
            mstore(add(o, 0x0), mload(h))
            mstore(add(o, 0x20), mload(add(h, 0x20)))
            mstore(add(o, 0x40), mload(add(h, 0x40)))
            for { let m := 0 } lt(m, 3) { m := add(m, 1) } {
                mstore(add(o, add(0x60, shl(5, m))), mload(add(roots, shl(5, add(m, 1)))))
                let be := mload(add(betas, shl(5, add(m, 1))))
                mstore(add(o, add(0xc0, shl(6, m))), mload(be))
                mstore(add(o, add(0xe0, shl(6, m))), mload(add(be, 0x20)))
            }
            for { let q := 0 } lt(q, 17) { q := add(q, 1) } {
                let pos := mload(add(idx, shl(5, add(q, 1))))
                mstore(add(o, add(0x180, shl(5, q))), pos)
                let e0, e1 := horner(xFinal(pos))
                mstore(add(o, add(0x3a0, shl(6, q))), e0)
                mstore(add(o, add(0x3c0, shl(6, q))), e1)
            }
            mstore(add(o, 0x7e0), mload(add(b, 0x120)))
            mstore(add(o, 0x800), mload(add(b, 0x140)))
            mstore(add(o, 0x820), mload(add(b, 0x160)))
            mstore(add(o, 0x840), mload(add(b, 0x180)))
            mstore(add(o, 0x860), mload(add(b, 0x1a0)))
            mstore(add(o, 0x880), mload(add(b, 0x1c0)))
            mstore(add(o, 0x8a0), mload(z))
            mstore(add(o, 0x8c0), mload(add(z, 0x20)))
            // kflat by the identity precompile
            if iszero(staticcall(gas(), 0x04, add(kf, 0x20), 0x24c0, add(o, 0x8e0), 0x24c0)) { revert(0, 0) }
            mstore(add(o, 0x2da0), 0xa0)



            return(o, 0x2dc0)

            // (7 omega^(pos mod 2^15))^256 = 7^256 (omega^256)^(pos mod 2^15), ProductionAir.xFinal
            function xFinal(pos) -> x {
                x := 0xfef45a869aab8679
                if and(pos, 0x1) { x := mulmod(x, 0xe0ee099310bba1e2, 0xffffffff00000001) }
                if and(pos, 0x2) { x := mulmod(x, 0x1544ef2335d17997, 0xffffffff00000001) }
                if and(pos, 0x4) { x := mulmod(x, 0xf2c35199959dfcb6, 0xffffffff00000001) }
                if and(pos, 0x8) { x := mulmod(x, 0x653b4801da1c8cf, 0xffffffff00000001) }
                if and(pos, 0x10) { x := mulmod(x, 0x9d8f2ad78bfed972, 0xffffffff00000001) }
                if and(pos, 0x20) { x := mulmod(x, 0x1905d02a5c411f4e, 0xffffffff00000001) }
                if and(pos, 0x40) { x := mulmod(x, 0xbf79143ce60ca966, 0xffffffff00000001) }
                if and(pos, 0x80) { x := mulmod(x, 0xf80007ff08000001, 0xffffffff00000001) }
                if and(pos, 0x100) { x := mulmod(x, 0x8000000000, 0xffffffff00000001) }
                if and(pos, 0x200) { x := mulmod(x, 0x3fffffffc000, 0xffffffff00000001) }
                if and(pos, 0x400) { x := mulmod(x, 0xefffffff00000001, 0xffffffff00000001) }
                if and(pos, 0x800) { x := mulmod(x, 0xfffffffeff000001, 0xffffffff00000001) }
                if and(pos, 0x1000) { x := mulmod(x, 0x1000000000000, 0xffffffff00000001) }
                if and(pos, 0x2000) { x := mulmod(x, 0xffffffff00000000, 0xffffffff00000001) }
            }

            // sum_j c_j x^j over the final layer at 0xa0, as RealQueryWalk._horner
            function horner(x) -> e0, e1 {
                e0 := mload(0x4060)
                e0 := add(mulmod(add(mul(add(mul(add(mul(e0, x), mload(0x4020)), x), mload(0x3fe0)), x), mload(0x3fa0)), x, 0xffffffff00000001), mload(0x3f60))
                e0 := add(mulmod(add(mul(add(mul(e0, x), mload(0x3f20)), x), mload(0x3ee0)), x, 0xffffffff00000001), mload(0x3ea0))
                e0 := add(mulmod(add(mul(add(mul(e0, x), mload(0x3e60)), x), mload(0x3e20)), x, 0xffffffff00000001), mload(0x3de0))
                e0 := add(mulmod(add(mul(add(mul(e0, x), mload(0x3da0)), x), mload(0x3d60)), x, 0xffffffff00000001), mload(0x3d20))
                e0 := add(mulmod(add(mul(add(mul(e0, x), mload(0x3ce0)), x), mload(0x3ca0)), x, 0xffffffff00000001), mload(0x3c60))
                e0 := add(mulmod(add(mul(add(mul(e0, x), mload(0x3c20)), x), mload(0x3be0)), x, 0xffffffff00000001), mload(0x3ba0))
                e0 := add(mulmod(add(mul(add(mul(e0, x), mload(0x3b60)), x), mload(0x3b20)), x, 0xffffffff00000001), mload(0x3ae0))
                e0 := add(mulmod(add(mul(add(mul(e0, x), mload(0x3aa0)), x), mload(0x3a60)), x, 0xffffffff00000001), mload(0x3a20))
                e0 := add(mulmod(add(mul(add(mul(e0, x), mload(0x39e0)), x), mload(0x39a0)), x, 0xffffffff00000001), mload(0x3960))
                e0 := add(mulmod(add(mul(add(mul(e0, x), mload(0x3920)), x), mload(0x38e0)), x, 0xffffffff00000001), mload(0x38a0))
                e0 := add(mulmod(add(mul(add(mul(e0, x), mload(0x3860)), x), mload(0x3820)), x, 0xffffffff00000001), mload(0x37e0))
                e0 := add(mulmod(add(mul(add(mul(e0, x), mload(0x37a0)), x), mload(0x3760)), x, 0xffffffff00000001), mload(0x3720))
                e0 := add(mulmod(add(mul(add(mul(e0, x), mload(0x36e0)), x), mload(0x36a0)), x, 0xffffffff00000001), mload(0x3660))
                e0 := add(mulmod(add(mul(add(mul(e0, x), mload(0x3620)), x), mload(0x35e0)), x, 0xffffffff00000001), mload(0x35a0))
                e0 := add(mulmod(add(mul(add(mul(e0, x), mload(0x3560)), x), mload(0x3520)), x, 0xffffffff00000001), mload(0x34e0))
                e0 := add(mulmod(add(mul(add(mul(e0, x), mload(0x34a0)), x), mload(0x3460)), x, 0xffffffff00000001), mload(0x3420))
                e0 := add(mulmod(add(mul(add(mul(e0, x), mload(0x33e0)), x), mload(0x33a0)), x, 0xffffffff00000001), mload(0x3360))
                e0 := add(mulmod(add(mul(add(mul(e0, x), mload(0x3320)), x), mload(0x32e0)), x, 0xffffffff00000001), mload(0x32a0))
                e0 := add(mulmod(add(mul(add(mul(e0, x), mload(0x3260)), x), mload(0x3220)), x, 0xffffffff00000001), mload(0x31e0))
                e0 := add(mulmod(add(mul(add(mul(e0, x), mload(0x31a0)), x), mload(0x3160)), x, 0xffffffff00000001), mload(0x3120))
                e0 := add(mulmod(add(mul(add(mul(e0, x), mload(0x30e0)), x), mload(0x30a0)), x, 0xffffffff00000001), mload(0x3060))
                e0 := add(mulmod(add(mul(add(mul(e0, x), mload(0x3020)), x), mload(0x2fe0)), x, 0xffffffff00000001), mload(0x2fa0))
                e0 := add(mulmod(add(mul(add(mul(e0, x), mload(0x2f60)), x), mload(0x2f20)), x, 0xffffffff00000001), mload(0x2ee0))
                e0 := add(mulmod(add(mul(add(mul(e0, x), mload(0x2ea0)), x), mload(0x2e60)), x, 0xffffffff00000001), mload(0x2e20))
                e0 := add(mulmod(add(mul(add(mul(e0, x), mload(0x2de0)), x), mload(0x2da0)), x, 0xffffffff00000001), mload(0x2d60))
                e0 := add(mulmod(add(mul(add(mul(e0, x), mload(0x2d20)), x), mload(0x2ce0)), x, 0xffffffff00000001), mload(0x2ca0))
                e0 := add(mulmod(add(mul(add(mul(e0, x), mload(0x2c60)), x), mload(0x2c20)), x, 0xffffffff00000001), mload(0x2be0))
                e0 := add(mulmod(add(mul(add(mul(e0, x), mload(0x2ba0)), x), mload(0x2b60)), x, 0xffffffff00000001), mload(0x2b20))
                e0 := add(mulmod(add(mul(add(mul(e0, x), mload(0x2ae0)), x), mload(0x2aa0)), x, 0xffffffff00000001), mload(0x2a60))
                e0 := add(mulmod(add(mul(add(mul(e0, x), mload(0x2a20)), x), mload(0x29e0)), x, 0xffffffff00000001), mload(0x29a0))
                e0 := add(mulmod(add(mul(add(mul(e0, x), mload(0x2960)), x), mload(0x2920)), x, 0xffffffff00000001), mload(0x28e0))
                e0 := add(mulmod(add(mul(add(mul(e0, x), mload(0x28a0)), x), mload(0x2860)), x, 0xffffffff00000001), mload(0x2820))
                e0 := add(mulmod(add(mul(add(mul(e0, x), mload(0x27e0)), x), mload(0x27a0)), x, 0xffffffff00000001), mload(0x2760))
                e0 := add(mulmod(add(mul(add(mul(e0, x), mload(0x2720)), x), mload(0x26e0)), x, 0xffffffff00000001), mload(0x26a0))
                e0 := add(mulmod(add(mul(add(mul(e0, x), mload(0x2660)), x), mload(0x2620)), x, 0xffffffff00000001), mload(0x25e0))
                e0 := add(mulmod(add(mul(add(mul(e0, x), mload(0x25a0)), x), mload(0x2560)), x, 0xffffffff00000001), mload(0x2520))
                e0 := add(mulmod(add(mul(add(mul(e0, x), mload(0x24e0)), x), mload(0x24a0)), x, 0xffffffff00000001), mload(0x2460))
                e0 := add(mulmod(add(mul(add(mul(e0, x), mload(0x2420)), x), mload(0x23e0)), x, 0xffffffff00000001), mload(0x23a0))
                e0 := add(mulmod(add(mul(add(mul(e0, x), mload(0x2360)), x), mload(0x2320)), x, 0xffffffff00000001), mload(0x22e0))
                e0 := add(mulmod(add(mul(add(mul(e0, x), mload(0x22a0)), x), mload(0x2260)), x, 0xffffffff00000001), mload(0x2220))
                e0 := add(mulmod(add(mul(add(mul(e0, x), mload(0x21e0)), x), mload(0x21a0)), x, 0xffffffff00000001), mload(0x2160))
                e0 := add(mulmod(add(mul(add(mul(e0, x), mload(0x2120)), x), mload(0x20e0)), x, 0xffffffff00000001), mload(0x20a0))
                e0 := add(mulmod(add(mul(add(mul(e0, x), mload(0x2060)), x), mload(0x2020)), x, 0xffffffff00000001), mload(0x1fe0))
                e0 := add(mulmod(add(mul(add(mul(e0, x), mload(0x1fa0)), x), mload(0x1f60)), x, 0xffffffff00000001), mload(0x1f20))
                e0 := add(mulmod(add(mul(add(mul(e0, x), mload(0x1ee0)), x), mload(0x1ea0)), x, 0xffffffff00000001), mload(0x1e60))
                e0 := add(mulmod(add(mul(add(mul(e0, x), mload(0x1e20)), x), mload(0x1de0)), x, 0xffffffff00000001), mload(0x1da0))
                e0 := add(mulmod(add(mul(add(mul(e0, x), mload(0x1d60)), x), mload(0x1d20)), x, 0xffffffff00000001), mload(0x1ce0))
                e0 := add(mulmod(add(mul(add(mul(e0, x), mload(0x1ca0)), x), mload(0x1c60)), x, 0xffffffff00000001), mload(0x1c20))
                e0 := add(mulmod(add(mul(add(mul(e0, x), mload(0x1be0)), x), mload(0x1ba0)), x, 0xffffffff00000001), mload(0x1b60))
                e0 := add(mulmod(add(mul(add(mul(e0, x), mload(0x1b20)), x), mload(0x1ae0)), x, 0xffffffff00000001), mload(0x1aa0))
                e0 := add(mulmod(add(mul(add(mul(e0, x), mload(0x1a60)), x), mload(0x1a20)), x, 0xffffffff00000001), mload(0x19e0))
                e0 := add(mulmod(add(mul(add(mul(e0, x), mload(0x19a0)), x), mload(0x1960)), x, 0xffffffff00000001), mload(0x1920))
                e0 := add(mulmod(add(mul(add(mul(e0, x), mload(0x18e0)), x), mload(0x18a0)), x, 0xffffffff00000001), mload(0x1860))
                e0 := add(mulmod(add(mul(add(mul(e0, x), mload(0x1820)), x), mload(0x17e0)), x, 0xffffffff00000001), mload(0x17a0))
                e0 := add(mulmod(add(mul(add(mul(e0, x), mload(0x1760)), x), mload(0x1720)), x, 0xffffffff00000001), mload(0x16e0))
                e0 := add(mulmod(add(mul(add(mul(e0, x), mload(0x16a0)), x), mload(0x1660)), x, 0xffffffff00000001), mload(0x1620))
                e0 := add(mulmod(add(mul(add(mul(e0, x), mload(0x15e0)), x), mload(0x15a0)), x, 0xffffffff00000001), mload(0x1560))
                e0 := add(mulmod(add(mul(add(mul(e0, x), mload(0x1520)), x), mload(0x14e0)), x, 0xffffffff00000001), mload(0x14a0))
                e0 := add(mulmod(add(mul(add(mul(e0, x), mload(0x1460)), x), mload(0x1420)), x, 0xffffffff00000001), mload(0x13e0))
                e0 := add(mulmod(add(mul(add(mul(e0, x), mload(0x13a0)), x), mload(0x1360)), x, 0xffffffff00000001), mload(0x1320))
                e0 := add(mulmod(add(mul(add(mul(e0, x), mload(0x12e0)), x), mload(0x12a0)), x, 0xffffffff00000001), mload(0x1260))
                e0 := add(mulmod(add(mul(add(mul(e0, x), mload(0x1220)), x), mload(0x11e0)), x, 0xffffffff00000001), mload(0x11a0))
                e0 := add(mulmod(add(mul(add(mul(e0, x), mload(0x1160)), x), mload(0x1120)), x, 0xffffffff00000001), mload(0x10e0))
                e0 := add(mulmod(add(mul(add(mul(e0, x), mload(0x10a0)), x), mload(0x1060)), x, 0xffffffff00000001), mload(0x1020))
                e0 := add(mulmod(add(mul(add(mul(e0, x), mload(0xfe0)), x), mload(0xfa0)), x, 0xffffffff00000001), mload(0xf60))
                e0 := add(mulmod(add(mul(add(mul(e0, x), mload(0xf20)), x), mload(0xee0)), x, 0xffffffff00000001), mload(0xea0))
                e0 := add(mulmod(add(mul(add(mul(e0, x), mload(0xe60)), x), mload(0xe20)), x, 0xffffffff00000001), mload(0xde0))
                e0 := add(mulmod(add(mul(add(mul(e0, x), mload(0xda0)), x), mload(0xd60)), x, 0xffffffff00000001), mload(0xd20))
                e0 := add(mulmod(add(mul(add(mul(e0, x), mload(0xce0)), x), mload(0xca0)), x, 0xffffffff00000001), mload(0xc60))
                e0 := add(mulmod(add(mul(add(mul(e0, x), mload(0xc20)), x), mload(0xbe0)), x, 0xffffffff00000001), mload(0xba0))
                e0 := add(mulmod(add(mul(add(mul(e0, x), mload(0xb60)), x), mload(0xb20)), x, 0xffffffff00000001), mload(0xae0))
                e0 := add(mulmod(add(mul(add(mul(e0, x), mload(0xaa0)), x), mload(0xa60)), x, 0xffffffff00000001), mload(0xa20))
                e0 := add(mulmod(add(mul(add(mul(e0, x), mload(0x9e0)), x), mload(0x9a0)), x, 0xffffffff00000001), mload(0x960))
                e0 := add(mulmod(add(mul(add(mul(e0, x), mload(0x920)), x), mload(0x8e0)), x, 0xffffffff00000001), mload(0x8a0))
                e0 := add(mulmod(add(mul(add(mul(e0, x), mload(0x860)), x), mload(0x820)), x, 0xffffffff00000001), mload(0x7e0))
                e0 := add(mulmod(add(mul(add(mul(e0, x), mload(0x7a0)), x), mload(0x760)), x, 0xffffffff00000001), mload(0x720))
                e0 := add(mulmod(add(mul(add(mul(e0, x), mload(0x6e0)), x), mload(0x6a0)), x, 0xffffffff00000001), mload(0x660))
                e0 := add(mulmod(add(mul(add(mul(e0, x), mload(0x620)), x), mload(0x5e0)), x, 0xffffffff00000001), mload(0x5a0))
                e0 := add(mulmod(add(mul(add(mul(e0, x), mload(0x560)), x), mload(0x520)), x, 0xffffffff00000001), mload(0x4e0))
                e0 := add(mulmod(add(mul(add(mul(e0, x), mload(0x4a0)), x), mload(0x460)), x, 0xffffffff00000001), mload(0x420))
                e0 := add(mulmod(add(mul(add(mul(e0, x), mload(0x3e0)), x), mload(0x3a0)), x, 0xffffffff00000001), mload(0x360))
                e0 := add(mulmod(add(mul(add(mul(e0, x), mload(0x320)), x), mload(0x2e0)), x, 0xffffffff00000001), mload(0x2a0))
                e0 := add(mulmod(add(mul(add(mul(e0, x), mload(0x260)), x), mload(0x220)), x, 0xffffffff00000001), mload(0x1e0))
                e0 := add(mulmod(add(mul(add(mul(e0, x), mload(0x1a0)), x), mload(0x160)), x, 0xffffffff00000001), mload(0x120))
                e0 := add(mul(add(mul(e0, x), mload(0xe0)), x), mload(0xa0))
                e0 := mod(e0, 0xffffffff00000001)
                e1 := mload(0x4080)
                e1 := add(mulmod(add(mul(add(mul(add(mul(e1, x), mload(0x4040)), x), mload(0x4000)), x), mload(0x3fc0)), x, 0xffffffff00000001), mload(0x3f80))
                e1 := add(mulmod(add(mul(add(mul(e1, x), mload(0x3f40)), x), mload(0x3f00)), x, 0xffffffff00000001), mload(0x3ec0))
                e1 := add(mulmod(add(mul(add(mul(e1, x), mload(0x3e80)), x), mload(0x3e40)), x, 0xffffffff00000001), mload(0x3e00))
                e1 := add(mulmod(add(mul(add(mul(e1, x), mload(0x3dc0)), x), mload(0x3d80)), x, 0xffffffff00000001), mload(0x3d40))
                e1 := add(mulmod(add(mul(add(mul(e1, x), mload(0x3d00)), x), mload(0x3cc0)), x, 0xffffffff00000001), mload(0x3c80))
                e1 := add(mulmod(add(mul(add(mul(e1, x), mload(0x3c40)), x), mload(0x3c00)), x, 0xffffffff00000001), mload(0x3bc0))
                e1 := add(mulmod(add(mul(add(mul(e1, x), mload(0x3b80)), x), mload(0x3b40)), x, 0xffffffff00000001), mload(0x3b00))
                e1 := add(mulmod(add(mul(add(mul(e1, x), mload(0x3ac0)), x), mload(0x3a80)), x, 0xffffffff00000001), mload(0x3a40))
                e1 := add(mulmod(add(mul(add(mul(e1, x), mload(0x3a00)), x), mload(0x39c0)), x, 0xffffffff00000001), mload(0x3980))
                e1 := add(mulmod(add(mul(add(mul(e1, x), mload(0x3940)), x), mload(0x3900)), x, 0xffffffff00000001), mload(0x38c0))
                e1 := add(mulmod(add(mul(add(mul(e1, x), mload(0x3880)), x), mload(0x3840)), x, 0xffffffff00000001), mload(0x3800))
                e1 := add(mulmod(add(mul(add(mul(e1, x), mload(0x37c0)), x), mload(0x3780)), x, 0xffffffff00000001), mload(0x3740))
                e1 := add(mulmod(add(mul(add(mul(e1, x), mload(0x3700)), x), mload(0x36c0)), x, 0xffffffff00000001), mload(0x3680))
                e1 := add(mulmod(add(mul(add(mul(e1, x), mload(0x3640)), x), mload(0x3600)), x, 0xffffffff00000001), mload(0x35c0))
                e1 := add(mulmod(add(mul(add(mul(e1, x), mload(0x3580)), x), mload(0x3540)), x, 0xffffffff00000001), mload(0x3500))
                e1 := add(mulmod(add(mul(add(mul(e1, x), mload(0x34c0)), x), mload(0x3480)), x, 0xffffffff00000001), mload(0x3440))
                e1 := add(mulmod(add(mul(add(mul(e1, x), mload(0x3400)), x), mload(0x33c0)), x, 0xffffffff00000001), mload(0x3380))
                e1 := add(mulmod(add(mul(add(mul(e1, x), mload(0x3340)), x), mload(0x3300)), x, 0xffffffff00000001), mload(0x32c0))
                e1 := add(mulmod(add(mul(add(mul(e1, x), mload(0x3280)), x), mload(0x3240)), x, 0xffffffff00000001), mload(0x3200))
                e1 := add(mulmod(add(mul(add(mul(e1, x), mload(0x31c0)), x), mload(0x3180)), x, 0xffffffff00000001), mload(0x3140))
                e1 := add(mulmod(add(mul(add(mul(e1, x), mload(0x3100)), x), mload(0x30c0)), x, 0xffffffff00000001), mload(0x3080))
                e1 := add(mulmod(add(mul(add(mul(e1, x), mload(0x3040)), x), mload(0x3000)), x, 0xffffffff00000001), mload(0x2fc0))
                e1 := add(mulmod(add(mul(add(mul(e1, x), mload(0x2f80)), x), mload(0x2f40)), x, 0xffffffff00000001), mload(0x2f00))
                e1 := add(mulmod(add(mul(add(mul(e1, x), mload(0x2ec0)), x), mload(0x2e80)), x, 0xffffffff00000001), mload(0x2e40))
                e1 := add(mulmod(add(mul(add(mul(e1, x), mload(0x2e00)), x), mload(0x2dc0)), x, 0xffffffff00000001), mload(0x2d80))
                e1 := add(mulmod(add(mul(add(mul(e1, x), mload(0x2d40)), x), mload(0x2d00)), x, 0xffffffff00000001), mload(0x2cc0))
                e1 := add(mulmod(add(mul(add(mul(e1, x), mload(0x2c80)), x), mload(0x2c40)), x, 0xffffffff00000001), mload(0x2c00))
                e1 := add(mulmod(add(mul(add(mul(e1, x), mload(0x2bc0)), x), mload(0x2b80)), x, 0xffffffff00000001), mload(0x2b40))
                e1 := add(mulmod(add(mul(add(mul(e1, x), mload(0x2b00)), x), mload(0x2ac0)), x, 0xffffffff00000001), mload(0x2a80))
                e1 := add(mulmod(add(mul(add(mul(e1, x), mload(0x2a40)), x), mload(0x2a00)), x, 0xffffffff00000001), mload(0x29c0))
                e1 := add(mulmod(add(mul(add(mul(e1, x), mload(0x2980)), x), mload(0x2940)), x, 0xffffffff00000001), mload(0x2900))
                e1 := add(mulmod(add(mul(add(mul(e1, x), mload(0x28c0)), x), mload(0x2880)), x, 0xffffffff00000001), mload(0x2840))
                e1 := add(mulmod(add(mul(add(mul(e1, x), mload(0x2800)), x), mload(0x27c0)), x, 0xffffffff00000001), mload(0x2780))
                e1 := add(mulmod(add(mul(add(mul(e1, x), mload(0x2740)), x), mload(0x2700)), x, 0xffffffff00000001), mload(0x26c0))
                e1 := add(mulmod(add(mul(add(mul(e1, x), mload(0x2680)), x), mload(0x2640)), x, 0xffffffff00000001), mload(0x2600))
                e1 := add(mulmod(add(mul(add(mul(e1, x), mload(0x25c0)), x), mload(0x2580)), x, 0xffffffff00000001), mload(0x2540))
                e1 := add(mulmod(add(mul(add(mul(e1, x), mload(0x2500)), x), mload(0x24c0)), x, 0xffffffff00000001), mload(0x2480))
                e1 := add(mulmod(add(mul(add(mul(e1, x), mload(0x2440)), x), mload(0x2400)), x, 0xffffffff00000001), mload(0x23c0))
                e1 := add(mulmod(add(mul(add(mul(e1, x), mload(0x2380)), x), mload(0x2340)), x, 0xffffffff00000001), mload(0x2300))
                e1 := add(mulmod(add(mul(add(mul(e1, x), mload(0x22c0)), x), mload(0x2280)), x, 0xffffffff00000001), mload(0x2240))
                e1 := add(mulmod(add(mul(add(mul(e1, x), mload(0x2200)), x), mload(0x21c0)), x, 0xffffffff00000001), mload(0x2180))
                e1 := add(mulmod(add(mul(add(mul(e1, x), mload(0x2140)), x), mload(0x2100)), x, 0xffffffff00000001), mload(0x20c0))
                e1 := add(mulmod(add(mul(add(mul(e1, x), mload(0x2080)), x), mload(0x2040)), x, 0xffffffff00000001), mload(0x2000))
                e1 := add(mulmod(add(mul(add(mul(e1, x), mload(0x1fc0)), x), mload(0x1f80)), x, 0xffffffff00000001), mload(0x1f40))
                e1 := add(mulmod(add(mul(add(mul(e1, x), mload(0x1f00)), x), mload(0x1ec0)), x, 0xffffffff00000001), mload(0x1e80))
                e1 := add(mulmod(add(mul(add(mul(e1, x), mload(0x1e40)), x), mload(0x1e00)), x, 0xffffffff00000001), mload(0x1dc0))
                e1 := add(mulmod(add(mul(add(mul(e1, x), mload(0x1d80)), x), mload(0x1d40)), x, 0xffffffff00000001), mload(0x1d00))
                e1 := add(mulmod(add(mul(add(mul(e1, x), mload(0x1cc0)), x), mload(0x1c80)), x, 0xffffffff00000001), mload(0x1c40))
                e1 := add(mulmod(add(mul(add(mul(e1, x), mload(0x1c00)), x), mload(0x1bc0)), x, 0xffffffff00000001), mload(0x1b80))
                e1 := add(mulmod(add(mul(add(mul(e1, x), mload(0x1b40)), x), mload(0x1b00)), x, 0xffffffff00000001), mload(0x1ac0))
                e1 := add(mulmod(add(mul(add(mul(e1, x), mload(0x1a80)), x), mload(0x1a40)), x, 0xffffffff00000001), mload(0x1a00))
                e1 := add(mulmod(add(mul(add(mul(e1, x), mload(0x19c0)), x), mload(0x1980)), x, 0xffffffff00000001), mload(0x1940))
                e1 := add(mulmod(add(mul(add(mul(e1, x), mload(0x1900)), x), mload(0x18c0)), x, 0xffffffff00000001), mload(0x1880))
                e1 := add(mulmod(add(mul(add(mul(e1, x), mload(0x1840)), x), mload(0x1800)), x, 0xffffffff00000001), mload(0x17c0))
                e1 := add(mulmod(add(mul(add(mul(e1, x), mload(0x1780)), x), mload(0x1740)), x, 0xffffffff00000001), mload(0x1700))
                e1 := add(mulmod(add(mul(add(mul(e1, x), mload(0x16c0)), x), mload(0x1680)), x, 0xffffffff00000001), mload(0x1640))
                e1 := add(mulmod(add(mul(add(mul(e1, x), mload(0x1600)), x), mload(0x15c0)), x, 0xffffffff00000001), mload(0x1580))
                e1 := add(mulmod(add(mul(add(mul(e1, x), mload(0x1540)), x), mload(0x1500)), x, 0xffffffff00000001), mload(0x14c0))
                e1 := add(mulmod(add(mul(add(mul(e1, x), mload(0x1480)), x), mload(0x1440)), x, 0xffffffff00000001), mload(0x1400))
                e1 := add(mulmod(add(mul(add(mul(e1, x), mload(0x13c0)), x), mload(0x1380)), x, 0xffffffff00000001), mload(0x1340))
                e1 := add(mulmod(add(mul(add(mul(e1, x), mload(0x1300)), x), mload(0x12c0)), x, 0xffffffff00000001), mload(0x1280))
                e1 := add(mulmod(add(mul(add(mul(e1, x), mload(0x1240)), x), mload(0x1200)), x, 0xffffffff00000001), mload(0x11c0))
                e1 := add(mulmod(add(mul(add(mul(e1, x), mload(0x1180)), x), mload(0x1140)), x, 0xffffffff00000001), mload(0x1100))
                e1 := add(mulmod(add(mul(add(mul(e1, x), mload(0x10c0)), x), mload(0x1080)), x, 0xffffffff00000001), mload(0x1040))
                e1 := add(mulmod(add(mul(add(mul(e1, x), mload(0x1000)), x), mload(0xfc0)), x, 0xffffffff00000001), mload(0xf80))
                e1 := add(mulmod(add(mul(add(mul(e1, x), mload(0xf40)), x), mload(0xf00)), x, 0xffffffff00000001), mload(0xec0))
                e1 := add(mulmod(add(mul(add(mul(e1, x), mload(0xe80)), x), mload(0xe40)), x, 0xffffffff00000001), mload(0xe00))
                e1 := add(mulmod(add(mul(add(mul(e1, x), mload(0xdc0)), x), mload(0xd80)), x, 0xffffffff00000001), mload(0xd40))
                e1 := add(mulmod(add(mul(add(mul(e1, x), mload(0xd00)), x), mload(0xcc0)), x, 0xffffffff00000001), mload(0xc80))
                e1 := add(mulmod(add(mul(add(mul(e1, x), mload(0xc40)), x), mload(0xc00)), x, 0xffffffff00000001), mload(0xbc0))
                e1 := add(mulmod(add(mul(add(mul(e1, x), mload(0xb80)), x), mload(0xb40)), x, 0xffffffff00000001), mload(0xb00))
                e1 := add(mulmod(add(mul(add(mul(e1, x), mload(0xac0)), x), mload(0xa80)), x, 0xffffffff00000001), mload(0xa40))
                e1 := add(mulmod(add(mul(add(mul(e1, x), mload(0xa00)), x), mload(0x9c0)), x, 0xffffffff00000001), mload(0x980))
                e1 := add(mulmod(add(mul(add(mul(e1, x), mload(0x940)), x), mload(0x900)), x, 0xffffffff00000001), mload(0x8c0))
                e1 := add(mulmod(add(mul(add(mul(e1, x), mload(0x880)), x), mload(0x840)), x, 0xffffffff00000001), mload(0x800))
                e1 := add(mulmod(add(mul(add(mul(e1, x), mload(0x7c0)), x), mload(0x780)), x, 0xffffffff00000001), mload(0x740))
                e1 := add(mulmod(add(mul(add(mul(e1, x), mload(0x700)), x), mload(0x6c0)), x, 0xffffffff00000001), mload(0x680))
                e1 := add(mulmod(add(mul(add(mul(e1, x), mload(0x640)), x), mload(0x600)), x, 0xffffffff00000001), mload(0x5c0))
                e1 := add(mulmod(add(mul(add(mul(e1, x), mload(0x580)), x), mload(0x540)), x, 0xffffffff00000001), mload(0x500))
                e1 := add(mulmod(add(mul(add(mul(e1, x), mload(0x4c0)), x), mload(0x480)), x, 0xffffffff00000001), mload(0x440))
                e1 := add(mulmod(add(mul(add(mul(e1, x), mload(0x400)), x), mload(0x3c0)), x, 0xffffffff00000001), mload(0x380))
                e1 := add(mulmod(add(mul(add(mul(e1, x), mload(0x340)), x), mload(0x300)), x, 0xffffffff00000001), mload(0x2c0))
                e1 := add(mulmod(add(mul(add(mul(e1, x), mload(0x280)), x), mload(0x240)), x, 0xffffffff00000001), mload(0x200))
                e1 := add(mulmod(add(mul(add(mul(e1, x), mload(0x1c0)), x), mload(0x180)), x, 0xffffffff00000001), mload(0x140))
                e1 := add(mul(add(mul(e1, x), mload(0x100)), x), mload(0xc0))
                e1 := mod(e1, 0xffffffff00000001)
            }
        }
    }
}
